### ISSUE TITLE
Prep for 0.26.2

### ISSUE THREAD

**Issue by joshka** [ratatui-org/ratatui#1025]
Ratatui 0.26.2 release will be a non-breaking release and then we'll release 0.27.0 with the breaking changes.

A quick TODO list:

- [ ] Determine any PRs that we want to get finished and into 0.26.2 @ratatui-org/maintainers.
- [ ] Determine if there are any easy-wins in the issues that we should fix
- [x] Write release post - @orhun?
- [x] Release @orhun 

My short list of PRs that I think probably should be in 0.26.2 is:
- https://github.com/ratatui-org/ratatui/pull/1001
- https://github.com/ratatui-org/ratatui/pull/991 ... maybe

**Comment by orhun** [comment]
Sounds good, thanks for creating the checklist. Let's aim for next Monday.

**Comment by joshka** [comment]
I may not personally get to either of the two things I listed before Monday due to other things on my plate. We can release without them however.

**Comment by orhun** [comment]
Ready for tomorrow, feel free to review:
- https://github.com/ratatui-org/ratatui/pull/1029
- https://github.com/ratatui-org/ratatui-website/pull/566

**Comment by orhun** [comment]
Release is completed 🧀

- https://github.com/ratatui-org/ratatui/releases/tag/v0.26.2
- https://crates.io/crates/ratatui
- https://ratatui.rs/highlights/v0262/
