### ISSUE TITLE
`assert_buffer_eq` missing `indoc`

### ISSUE THREAD

**Issue by tgross35** [ratatui-org/ratatui#1043]
## Description

Trying to use `assert_buffer_eq` results in:

```text
error[E0433]: failed to resolve: use of undeclared crate or module `indoc`
  --> tests/basic.rs:32:5
   |
32 |     assert_buffer_eq!(buf, expected);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `indoc`
   |
   = note: this error originates in the macro `assert_buffer_eq` (in Nightly builds, run with -Z macro-backtrace for more info
```

The macro makes use of `indoc` directly, but should probably add something like:

```rust
#[doc(hidden)]
pub mod __private {
    pub use indoc;
}
```

And use `$crate::__private::indoc::...` within `assert_buffer_eq`.

## To Reproduce
Use `assert_buffer_eq!` without `indoc` as a direct dependency. This goes away by adding `indoc`.

## Expected behavior

No error

## Environment
- OS: Linux
- Terminal Emulator: Windows Terminal
- Font: Default
- Crate version: 0.26.2
- Backend: crossterm

**Comment by EdJoPaTo** [comment]
#1007 removes the use of indoc from the macro (which is a normal function then) so this should be gone with that PR too.

**Comment by kdheepak** [comment]
As a temporary workaround, I've been adding `indoc` as a dev dependency which seems to solve this.

**Comment by joshka** [comment]
I'm going to close this issue out as as there's an easy workaround and it will not be an issue in the future.
