### ISSUE TITLE
Constraints example does not handle keys correctly on Windows

### ISSUE THREAD

**Issue by psobolik** [ratatui-org/ratatui#1062]
## Description

The Constraints example program does not work correctly on Windows. Key events are duplicated. 

## To Reproduce

Run the example from a Window terminal. Press any of the navigation keys -- up, down, left, right, h,  j, k or l.

## Expected behavior

The next or previous tab should be selected, or the content should be scrolled up or down one line.

## Environment

- OS: Windows
- Terminal Emulator: Windows Terminal or Cmd
- Font: N/A
- Crate version: N/A
- Backend: Crossterm

## Additional context

The problem is that the `handle_events` function does not apply the necessary `key.kind == KeyEventKind::Press` check as documented here: https://github.com/ratatui-org/ratatui/issues/347

**Comment by joshka** [comment]
Hey there - I wonder if you'd like to submit a PR to fix this? It's probably just a single line fix similar to the other examples where we do the check.
