### ISSUE TITLE
Features documentation on docs.rs isn't right.

### ISSUE THREAD

**Issue by matta** [ratatui-org/ratatui#1176]
## Description

The bottom of the features section at https://docs.rs/ratatui/latest/ratatui/#features contains appears to go awry after `unstable-widget-ref`. See screenshot:

![image](https://github.com/ratatui-org/ratatui/assets/37314/bdbd60da-3467-4c60-b62b-0eaf748eed6a)

## Additional context

I took a stab at fixing this, but I'm having trouble getting a successful doc build.

**Comment by matta** [comment]
Hmm, so I fixed my doc build (the doc-open job in the bacon config) by deleting the `Cargo.lock` file. With the current nightly and freshest dependencies, I cannot repro what I see on docs.rs.

Feel free to close this if it is uninteresting.

**Comment by orhun** [comment]
I am also unable to reproduce (even with `--all-features` flag), weird.

**Comment by joshka** [comment]
This was already fixed in https://github.com/ratatui-org/ratatui/commit/2f8a9363fc6c54fe2b10792c9f57fbb40b06bc0f
