### ISSUE TITLE
Add scroll by methods to list and table

### ISSUE THREAD

**Issue by joshka** [ratatui-org/ratatui#1207]
## Problem
Implement PageUp / Down like functionality
Suggested via https://github.com/intuis/rustmission/issues/13

## Solution
- work out exactly how to name this (not sure if this should be scroll_by(i32) or scroll_up_by(u16)/scroll_down_by(u16)
- implement

**Comment by josueBarretogit** [comment]
I think the methods should be called `scroll_down_with(steps : u32)` `scroll_up_with(steps: u32)` since TableState and ListState have methods using "with" like `with_offset` and `with_selected`, as for the numeric type of the methods I am not sure

**Comment by joshka** [comment]
`with` has too much constructor `with_` prefix vibe for my liking. the rationale of needing i32 was that i16 only covers half the range of u16, so when splitting the methods these would just need u16. I'm definitely inclined to split these and not make it a single method.

**Comment by josueBarretogit** [comment]
So `scroll_down_by(u16)` and `scroll_up_by(u16)` works fine too, i was wondering this feature would allow for scrolling like in vim? for example the user could type 4 and then j and it would scroll down 4 times right?

**Comment by joshka** [comment]
yep

**Comment by josueBarretogit** [comment]
Nice, I want to contribute to this issue so I will keep an eye on this until the design is defined

**Comment by joshka** [comment]
In the absence of other feedback, let's go ahead with `scroll_up/down_by(u16)` - feel free to submit a PR for this.
