### ISSUE TITLE
Support for Lines as Chart Labels

### ISSUE THREAD

**Issue by nullstalgia** [ratatui-org/ratatui#1272]
Continuing from a comment in #1227

Howdy howdy.

I have [an app](https://github.com/nullstalgia/null_iron_heart) I just released using Ratatui, and it was fun learning Rust and this crate! Thanks for maintaining such a cool tool!

And in that app, I have a chart that shows two data sets, correlated, but at different scales. I'm able to do the math to scale them so it appears properly, but I still need to label the bounds of each dataset. I would like to color-code the portions of the labels that correspond to which dataset to differentiate them, but instead I have to rely on parentheses.

Since styling is limited to per-Span, and I can't have a Line as a Label, I'm at an em passe.

![354025593-2675c211-4dda-420b-891e-17ffdc4d9a2b](https://github.com/user-attachments/assets/740dc74f-190c-4c17-ae08-b17d4b857dc7)

Shown is a screenshot of the app in question, and where I would like to apply the stylings.

**Comment by joshka** [comment]
Give #1273 a whirl to check if it does what you need.

**Comment by nullstalgia** [comment]
Wow! I didn't expect a patch so soon!

![image](https://github.com/user-attachments/assets/073309af-ee52-43e9-8e72-607c22f9140e)

Seems to work well! (Although I'll need to think of a smarter way to define them, since the Line and Span constructors are pretty "bulky.")

(My before and after, and after is without the if :P)
```rust
    // let labels = if render_bpm && render_rr {
    //     vec![
    //         format!("{} ({:.1})", bpm_bounds[0], rr_bounds[0]).bold(),
    //         format!("{} ({:.1})", avg_bpm, avg_rr).bold(),
    //         format!("{} ({:.1})", bpm_bounds[1], rr_bounds[1]).bold(),
    //     ]
    // } else if render_bpm {
    //     vec![
    //         format!("{}", bpm_bounds[0]).bold(),
    //         format!("{}", avg_bpm).bold(),
    //         format!("{}", bpm_bounds[1]).bold(),
    //     ]
    // } else {
    //     vec![
    //         format!("{:.1}", rr_bounds[0]).bold(),
    //         format!("{:.1}", avg_rr).bold(),
    //         format!("{:.1}", rr_bounds[1]).bold(),
    //     ]
    // };

    let labels = vec![
        Line::from(vec![
            Span::styled(
                bpm_bounds[0].to_string(),
                Style::default().fg(Color::Red).add_modifier(Modifier::BOLD),
            ),
            Span::styled(
                format!(" ({:.1})", rr_bounds[0]),
                Style::default().fg(Color::LightBlue),
            ),
        ]),
        Line::from(vec![
            Span::styled(
                mid_bpm.to_string(),
                Style::default().fg(Color::Red).add_modifier(Modifier::BOLD),
            ),
            Span::styled(
                format!(" ({:.1})", mid_rr),
                Style::default().fg(Color::LightBlue),
            ),
        ]),
        Line::from(vec![
            Span::styled(
                bpm_bounds[1].to_string(),
                Style::default().fg(Color::Red).add_modifier(Modifier::BOLD),
            ),
            Span::styled(
                format!(" ({:.1})", rr_bounds[1]),
                Style::default().fg(Color::LightBlue),
            ),
        ]),
    ];
```

Having it *under* the red number might also look nice, but I'm very happy with this improvement already!! Having Paragraphs as labels seems silly anyway :P

---

But thank you again! While I'm in the issues, I might open one more (unless I missed what I wanted in the documentation).

As you can see, I prefer the Red line to overlay on top of the blue, but that means that it's lower on the legend (which doesn't match the emphasis I want). Is there a way to reverse the legend direction?

**Comment by joshka** [comment]
> Seems to work well! (Although I'll need to think of a smarter way to define them, since the Line and Span constructors are pretty "bulky.")

https://crates.io/crates/ratatui-macros/ gives you:
```rust
    let labels = vec![
        line![
            span!((Color::Red, Modifier::BOLD); bpm_bounds[0]),
            span!(Color::LightBlue; " ({:.1})", rr_bounds[0]),
        ]),
        line![ ... ],
        line![ ... ],
    ];
```
I'd suggest also to take a look at the tuple to style conversions and store each of those in a variable.
You can also still do e.g. `bpm_bounds[0].red().bold()` etc.

> As you can see, I prefer the Red line to overlay on top of the blue, but that means that it's lower on the legend (which doesn't match the emphasis I want). Is there a way to reverse the legend direction?

No - but that probably requires a bit more design than the labels, as it implies a few things (order of drawing, order of labels, etc.). Feel free to cut an issue, but it might be a longer wait on an implementation than this one (which I had a pretty good idea on exactly how to do already). If I was writing an app, I'd probably just turn off the chart legend and manually draw it (it's a box with some text in it, so this shouldn't be super difficult).
