### ISSUE TITLE
Garbage key events on startup?

### ISSUE THREAD

**Issue by SUPERCILEX** [ratatui-org/ratatui#1275]
## Description

I'm occasionally seeing random garbage key events immediately on startup:
```
[tui/src/main.rs:383:5] &event = Key(
    KeyEvent {
        code: Char(
            '?',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
[tui/src/main.rs:383:5] &event = Key(
    KeyEvent {
        code: Char(
            '6',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
[tui/src/main.rs:383:5] &event = Key(
    KeyEvent {
        code: Char(
            '5',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
[tui/src/main.rs:383:5] &event = Key(
    KeyEvent {
        code: Char(
            ';',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
[tui/src/main.rs:383:5] &event = Key(
    KeyEvent {
        code: Char(
            '1',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
[tui/src/main.rs:383:5] &event = Key(
    KeyEvent {
        code: Char(
            ';',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
[tui/src/main.rs:383:5] &event = Key(
    KeyEvent {
        code: Char(
            '9',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
[tui/src/main.rs:383:5] &event = Key(
    KeyEvent {
        code: Char(
            'c',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
```

Here's another bit of garbage:
```
[tui/src/main.rs:383:5] &event = Key(
    KeyEvent {
        code: Char(
            '[',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
[tui/src/main.rs:383:5] &event = Key(
    KeyEvent {
        code: Char(
            '?',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
[tui/src/main.rs:383:5] &event = Key(
    KeyEvent {
        code: Char(
            '6',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
[tui/src/main.rs:383:5] &event = Key(
    KeyEvent {
        code: Char(
            '5',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
[tui/src/main.rs:383:5] &event = Key(
    KeyEvent {
        code: Char(
            ';',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
[tui/src/main.rs:383:5] &event = Key(
    KeyEvent {
        code: Char(
            '1',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
[tui/src/main.rs:383:5] &event = Key(
    KeyEvent {
        code: Char(
            ';',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
[tui/src/main.rs:383:5] &event = Key(
    KeyEvent {
        code: Char(
            '9',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
[tui/src/main.rs:383:5] &event = Key(
    KeyEvent {
        code: Char(
            'c',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
```

## To Reproduce

Can't figure out anything consistent.

## Environment

- OS: Linux
- Terminal Emulator: has occurred in Gnome terminal and COSMIC terminal
- Font:
- Crate version: 0.27
- Backend: crossterm

**Comment by orhun** [comment]
My first guess is those might be ANSI escape codes that are feeded into the TUI for some reason.

> [?65;1;9;c
> This specific code appears to be part of a Device Status Report (DSR) command sequence.

But there is no way to be sure without more info/samples.

I'm curious how you log these events.

**Comment by SUPERCILEX** [comment]
I put a `dbg!(&event);` right here: https://github.com/SUPERCILEX/clipboard-history/blob/bdf4aead1f0bcf81f71c476e539f3ad997aa1212/tui/src/main.rs#L382 and events from here: https://github.com/SUPERCILEX/clipboard-history/blob/bdf4aead1f0bcf81f71c476e539f3ad997aa1212/tui/src/main.rs#L201

I'll see if I can get more samples.

**Comment by SUPERCILEX** [comment]
```
[tui/src/main.rs:382:5] &event = Key(
    KeyEvent {
        code: Char(
            'c',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
```

```
[tui/src/main.rs:382:5] &event = Key(
    KeyEvent {
        code: Char(
            '6',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
[tui/src/main.rs:382:5] &event = Key(
    KeyEvent {
        code: Char(
            'c',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
```

```
[tui/src/main.rs:382:5] &event = Key(
    KeyEvent {
        code: Char(
            '?',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
[tui/src/main.rs:382:5] &event = Key(
    KeyEvent {
        code: Char(
            '6',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
[tui/src/main.rs:382:5] &event = Key(
    KeyEvent {
        code: Char(
            'c',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
```

```
[tui/src/main.rs:382:5] &event = Key(
    KeyEvent {
        code: Char(
            ';',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
[tui/src/main.rs:382:5] &event = Key(
    KeyEvent {
        code: Char(
            '9',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
[tui/src/main.rs:382:5] &event = Key(
    KeyEvent {
        code: Char(
            'c',
        ),
        modifiers: KeyModifiers(
            0x0,
        ),
        kind: Press,
        state: KeyEventState(
            0x0,
        ),
    },
)
```

*When* it occurs is super inconsistent, but it does looks like the set of characters it's trying to spit out is consistent.

**Comment by joshka** [comment]
This is more of a crossterm problem than a Ratatui one, so it might be worth asking at https://github.com/crossterm-rs/crossterm for more info on this. The only things that might be Ratatui specific are any calls to crossterm terminal functions that report back strings on the stdin / terminal tty. As far as I know we don't have anything that does this, but there could be something somewhere in the stack that I'm unaware of.

I'd be looking at whether you're fully restoring the termios after running the app. I.e. perhaps you're enabling the mouse capture but not disabling it when exiting, or something similar?

**Comment by kdheepak** [comment]
wezterm seem to have explicit support for Device Attributes, so you can read more about this in the source code:

https://github.com/wez/wezterm/blob/56a27e93a9ee50aab50ff4d78308f9b3154b5122/termwiz/src/escape/csi.rs#L3115-L3129

https://github.com/wez/wezterm/blob/56a27e93a9ee50aab50ff4d78308f9b3154b5122/term/src/terminalstate/mod.rs#L1283-L1293

My guess is somewhere in your application there's a request for device attributes and the response is being read by crossterm instead. You can either 1) remove dependencies one by one to filter down to when the issue doesn't happen, and then once you identify the dependency filter down to the lines of code there that is being called, and wrap that with a `disable_raw_mode` and `enable_raw_mode`, 2) you can handle the response yourself by reading the keycodes you get from crossterm (if you do handle it yourself, the dependency that made the request will no longer get the response, and may not function correctly).

You can also try to move your terminal init to as "late" as possible and see if that helps.

**Comment by joshka** [comment]
https://github.com/SUPERCILEX/clipboard-history/blob/bdf4aead1f0bcf81f71c476e539f3ad997aa1212/tui/src/main.rs#L225-L226

        let mut picker = Picker::from_termios().unwrap_or_else(|_| Picker::new((2, 4)));
        picker.guess_protocol();

https://docs.rs/ratatui-image/latest/ratatui_image/picker/struct.Picker.html#method.from_termios

> Query terminal for font-size with some escape sequence.
> This writes and reads from stdin momentarily.

https://docs.rs/ratatui-image/latest/ratatui_image/picker/struct.Picker.html#method.guess_protocol (also does stdout/in write/reads. See https://docs.rs/ratatui-image/latest/src/ratatui_image/picker.rs.html#103-106 and  https://docs.rs/ratatui-image/latest/src/ratatui_image/picker.rs.html#185-187

```rust
// Guess what protocol should be used, first from some program-specific magical env vars, then with
// the typical $TERM* env vars, and then with termios stdin/out queries.
```

These probably need to happen before you start reading events. You're starting the event reading thread before this code is run.

**Comment by SUPERCILEX** [comment]
Oh shit well that's embarrassing :sob:. Thank you so much for finding that! I created https://github.com/benjajaja/ratatui-image/pull/33 to hopefully help people avoid that mistake in the future.

**Comment by SUPERCILEX** [comment]
Thank you to everybody!
