### ISSUE TITLE
List: Allow alignment for `List` widget.

### ISSUE THREAD

**Issue by Xithrius** [ratatui-org/ratatui#131]
## Problem

As far as I am aware, there is no built-in way to align a list to the center of the terminal window. The only way that I know of is to add spaces before a string within a `ListItem` to be able to pad it towards the right side.

## Solution

Given that there's an alignment method for `Paragraph`, perhaps making this available across other widgets would be nice. 

Method would be accessible to the `List` widget:

Entire list:
```rust
let list = List::new(items)
    .style(Style::default().fg(Color::White))
    .highlight_style(Style::default().add_modifier(Modifier::ITALIC))
    .alignment(Alignment::Center);
```

## Alternatives

None that I know about.

**Comment by joshka** [comment]
This also seems like it will be fixed by a WidgetListWidget which is WIP over at https://github.com/tui-rs-revival/ratatui/issues/132 (and a related PR).

**Comment by Valentin271** [comment]
I'm closing this since you can align list items since 0.25 like that:

```rust
List::new([
    Line::from("left").alignment(Alignment::Left),
    Line::from("center").alignment(Alignment::Center),
    Line::from("right").alignment(Alignment::Right),
]);
```

Feel free to reopen an issue if needed.

**Comment by MadeInShineA** [comment]
This works, but then if there is an .highlight_symbol(">>"), it doesn't get aligned with the line an stays on the left

I think allowing the List itself to have the .alignment, and make it align all the content of the list (highlight symbol + List items) would probably be better ?

Is there any way around this ?

**Comment by orhun** [comment]
Yup, sounds like you are describing the expected behavior.

Please file a new issue for this (with a code snippet & screenshots if possible) :)
