### ISSUE TITLE
Convert the buffer type into a trait with the current buffer as one of it's implementations

### ISSUE THREAD

**Issue by giocri** [ratatui-org/ratatui#1450]
## Problem

Currently the only way to handle operations such as creating a scrollable area with multiple widgets or force transparency onto a widget is to create a separtate buffer for widgets to render onto and then copying portions of it on the final buffer whith the associated performance cost

## Solution

creating a trait with the current interface of the struct Buffer and use that inside the widget traits instead of buffer directly. this would allow users to create their own types capable of acting as decorators to Buffer and perform operations such as cropping or offsetting the area where a widget is rendered or prevent the wideget from overriding part of what was previusly drawn in that area

Performance: this approach should not introduce any performance drawbacks to users that use the default Buffer
Compatibility: altering the definition of the widget trait would indirectly affect the interface of all existing widgets but migration should remain
                       relatively painless as there would not be any required change in the internal behaviors of widgets

**Comment by orhun** [comment]
Thanks for creating the issue!

This was also discussed in [this forum post](https://forum.ratatui.rs/t/brainstorming-redesigns/107)
The same issue was described in [this comment](https://github.com/ratatui/ratatui-website/pull/725#issuecomment-2379751322).

We need to discuss this first probably so I'm converting this to a discussion :)
