### ISSUE TITLE
Nightly releases

### ISSUE THREAD

**Issue by orhun** [ratatui-org/ratatui#147]
## Problem

There might be some time gaps between new releases so the users cannot test/use the latest functionality without using `ratatui` as a `git` dependency in `Cargo.toml` which makes the crate _unpublishable_ on crates.io. (crates.io doesn't accept `git` dependencies)

See what `atuin` did recently as a workaround: https://github.com/ellie/atuin/commit/a515b06bcb556c1be2d0fc3095cd778d413fe40d

## Solution

Create automated nightly releases every week or so. `ratatui` can be used as e.g. `version = "nightly-2023-04-21"` afterwards. 

## Alternatives

Just plan things out and release more frequently.

## Additional context

None.

---

We need comments/thoughts on this.

**Comment by mindoodoo** [comment]
This is a great idea, having automated nightly releases will help us a lot.

How often though ?

I think depending on activity something like every two weeks might be good, maybe every week might be a bit excessive, let's hear other peoples thoughts on this though !

Looking forward to this 🚀

**Comment by sophacles** [comment]
Why not every day that there's been a merge that changes the code or docs? 

Should the version be `nightly-$date` or something like `$next_version-alpha.$N` (so if we start today, `0.21.0-alpha.1`  from my reading of https://doc.rust-lang.org/cargo/reference/resolver.html#pre-releases I'm no sure how `nightly-date` would be handled or ordered relative to other things.

I know when I'm working on a project, and I know a feature is merged but not released, I'd like to have updates by setting `version=....-alpha` as I'm developing my stuff.

**Comment by sayanarijit** [comment]
Inviting @extrawurst to the conversation.

**Comment by extrawurst** [comment]
I like the idea of daily releases iff there was a change.

**Comment by mindoodoo** [comment]
Someone also mentioned on discord that separating these releases to another repo might be interesting in order to not inundate people with release notifications from the main repo.

**Comment by extrawurst** [comment]
> Someone also mentioned on discord that separating these releases to another repo might be interesting in order to not inundate people with release notifications from the main repo.

yeah having nightly or even weekly releases/tags might become noisy.

**Comment by mindoodoo** [comment]
Reviving this issue following the 18/07/2023 general meeting &rarr; #316

>  -  General consensus is that we should set up nightly releases
    - Frequency → once per week
        - With option to trigger manually in case by case basis

cc: @orhun @joshka

**Comment by orhun** [comment]
I will be working on a GitHub Actions workflow file soon!

**Comment by mindoodoo** [comment]
Awesome thanks !

**Comment by orhun** [comment]
Just realized `crates.io` does not recognize `nightly-<date>` versioning schema as pre-release so we need to go with either e.g. `0.22.0-beta.0` or `0.22.0-alpha.0`. Any thoughts?

**Comment by joshka** [comment]
Strong opinion: `-alpha.0` for nightlies.

Use `-alpha` to indicate that the next release will happen whenever there is more commits merged on that day. There's no contract that these won't introduce bugs, or unwanted changes in behavior. Effectively no hard commitment to quality.

Use `-beta` to indicate that the release on the path to stabilization, and that the release was intentional rather than just something that happened. You might use this to test that a large change or new feature works in some app before releasing that version of ratatui to the wild.
