### ISSUE TITLE
Docs: Async example

### ISSUE THREAD

**Issue by lcmgh** [ratatui-org/ratatui#210]
## Problem
Could you provide an example such as https://github.com/tui-rs-revival/ratatui/blob/main/examples/user_input.rs that demonstrates how to use ratatui with Tokio?  

Nowadays there are many libs that provide async versions only (such as the official AWS SDK).

My use case is that I have to trigger some async fn when receiving user input.

## Alternatives
* Channels

**Comment by joshka** [comment]
Take a look at https://github.com/toot-rs/toot-rs/blob/main/src/event.rs (and main, app) for how I did it in toot-rs. I wouldn't class it as the best code, but it's an example of a few different async things. I struggled for a bit to find a good way of incorporating multiple screens that each had async workflows and settled on the approach in there - please don't take it as prescriptive, just as one approach that worked for me :)

**Comment by joshka** [comment]
There are a number of resources available in the ratatui book for this now:
- https://ratatui.rs/tutorial/counter-async-app/index.html
- https://ratatui.rs/tutorial/stopwatch-app/index.html (not really a tutorial yet)
- https://ratatui.rs/faq/tokio-async.html
- https://github.com/ratatui-org/ratatui-async-template

Closing this out for now. Feel free to reopen if needed.
