### ISSUE TITLE
intersects panic at ratatui-0.21.0/src/layout.rs:476:16

### ISSUE THREAD

**Issue by xizheyin** [ratatui-org/ratatui#251]
## Description

This testcase will trigger bugs in ratatui-0.21.0/src/layout.rs:476:16

## To Reproduce

```
fn main() {
    let _local3 = ratatui::layout::Rect::new(11051, 11051, 65280, 0);
    let _local4 = ratatui::layout::Rect::new(11051, 11051, 11051, 11037);
    let _ = ratatui::layout::Rect::intersects(_local3, _local4);
}
```

## Error Message

```
thread 'main' panicked at 'attempt to add with overflow', /home/yxz/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/ratatui-0.21.0/src/layout.rs:476:16
```

## Screenshots

![image](https://github.com/tui-rs-revival/ratatui/assets/62123683/dbc33970-3887-4cbe-9b29-969f77f87472)

**Comment by sayanarijit** [comment]
Please stop creating redundant issues for such edge cases. A single issue should be enough for a cleanup. If you want to contribute, please create a single issue or a single cleanup PR where we can have proper discussions. Closing this.
