### ISSUE TITLE
Rect: Arithmetic overflow occurs in intersection, intersects, and union

### ISSUE THREAD

**Issue by XizheYin-NJU** [ratatui-org/ratatui#258]
## Description

I used the fuzzy-testing tool to find 14 different panics in this library, and they are all arithmetic overflow bugs. These bugs, while similar in appearance, require different constraints to be met in order to trigger.

This library is related to the graphical interface, so it can be considered to avoid some calculation overflow errors when processing graphics to ensure the robustness of the program.

If you have time, you can see if it needs to be repaired. I'm also willing to contribute code if I can. Thank you very much for taking the time to check my issue.

## To Reproduce

The replay files is in this [repo](https://github.com/XizheYin-NJU/replay_file/).

- replay1-replay6 will trigger different panic in `intersection`
- replay7-replay10 will trigger different panic in `intersects`
- replay11-replay14 will trigger different panic in `union`

## Additional context

The red rectangles marked in the diagram are the locations where the integer overflow error occurred.
![image](https://github.com/tui-rs-revival/ratatui/assets/62123683/48faaad8-68b2-4295-9d9f-baaf083a120e)

**Comment by haydenflinner** [comment]
Seems like it's better to let it overflow and panic in debug builds, then let the user who encounters this decide what to do. My ultrawide with a terminal maximized and font unreadably small is <1000 chars wide, so the action to take when we hit 32k cols wide seems like an open question. Simply replacing every naive add/subtract with a saturating add/subtract would avoid panics, but likely lead to things not working as expected (for example, if you would have hit overflow while calculating intersects(), what is the desired behavior?). So better to keep the panic until someone hits this use-case.

**Comment by joshka** [comment]
The overflows here should just be clamped at 0 / u16:MAX as a Rect that is outside of those bounds isn't a Rect in Ratatui.
So I changed the various places that add x and width to instead call `.right()` which already saturates and similarly y+height -> bottom().

With intersection and union, again it only makes sense to deal with the part of the Rect that is actually a valid Rect, not the part outside of the bounds.

Ideally we should probably enforce constructors to make representing bad Rects with offscreen widths not actually possible.
