### ISSUE TITLE
Chore: implement common traits

### ISSUE THREAD

**Issue by joshka** [ratatui-org/ratatui#307]
## Description

All types should when possible implement the common traits.
https://rust-lang.github.io/api-guidelines/interoperability.html#c-common-traits

This allows consumers of the library to derive these traits themselves when needed rather than having to make manual implementations or avoid them.

Many of the types in ratatui do not implement these traits that could do so (particularly Hash is absent most of the time).

## To Reproduce

Example: Try to create a type that derives `Hash` and has a `Style` field

## Expected behavior

All common traits that make sense from https://rust-lang.github.io/api-guidelines/interoperability.html#c-common-traits should be implemented
- [Copy](https://doc.rust-lang.org/std/marker/trait.Copy.html) - Not possible for some items
- [Clone](https://doc.rust-lang.org/std/clone/trait.Clone.html)
- [Eq](https://doc.rust-lang.org/std/cmp/trait.Eq.html)
- [PartialEq](https://doc.rust-lang.org/std/cmp/trait.PartialEq.html)
- [Ord](https://doc.rust-lang.org/std/cmp/trait.Ord.html) - Usually not necessary
- [PartialOrd](https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html) - Usually not necessary
- [Hash](https://doc.rust-lang.org/std/hash/trait.Hash.html)
- [Debug](https://doc.rust-lang.org/std/fmt/trait.Debug.html)
- [Display](https://doc.rust-lang.org/std/fmt/trait.Display.html) - Not sure what this should look like TBH
- [Default](https://doc.rust-lang.org/std/default/trait.Default.html) - Sometimes not

**Comment by TieWay59** [comment]
Hi @joshka , I have one question: 

Is is OK to split this task up? I did small search and I have found too many structs that scatter around the code base, if someone raise a PR with trivial changes in different files and logic, it would be hard for others to review I guess. WDUT?

| Struct Name         | Debug | Default | PartialEq | Eq | Clone | Copy | Hash | FromArgs |
|---------------------|-------|---------|-----------|----|-------|------|------|----------|
| SinSignal           |   -   |   -     |     -     |  - |   ✔️   |  -   |  -   |    -     |
| Label               |   -   |   ✔️     |     -     |  - |   -   |  -   |  -   |    -     |
| App                 |   -   |   ✔️     |     -     |  - |   -   |  -   |  -   |    -     |
| RandomSignal        |   -   |   -     |     -     |  - |   ✔️   |  -   |  -   |    -     |
| Cli                 |   ✔️   |   -     |     -     |  - |   -   |  -   |  -   |   ✔️     |
| Cell                |   ✔️   |   -     |   ✔️     | ✔️ |   ✔️   |  -   |  -   |    -     |
| Buffer              |   -   |   ✔️     |   ✔️     | ✔️ |   ✔️   |  -   |  -   |    -     |
| Corner              |   ✔️   |   -     |   ✔️     | ✔️ |   ✔️   | ✔️   | ✔️   |    -     |
| Direction           |   ✔️   |   -     |   ✔️     | ✔️ |   ✔️   |  -   | ✔️   |    -     |
| Constraint          |   ✔️   |   -     |   ✔️     | ✔️ |   ✔️   | ✔️   | ✔️   |    -     |
...and so on.

**Comment by TieWay59** [comment]
For example, structs in `src/widgets/*.rs`:

| Struct Name            | Debug | Default | PartialEq | Eq | Clone | Hash |
|------------------------|-------|---------|-----------|----|-------|------|
| Padding                | ✔️     |   -     | ✔️       | ✔️  | ✔️     | ✔️   |
| Block<'a>              | ✔️     |   -     | ✔️       | ✔️  | ✔️     | -    |
| Monthly<'a, S: DateStyler> | -     |   -     | -         | -  | -     | -    |
| CalendarEventStore     | -     |   -     | -         | -  | -     | -    |
| Axis<'a>               | ✔️     |   -     | -         | -  | ✔️     | -    |
| Dataset<'a>            | ✔️     |   -     | -         | -  | ✔️     | -    |
| Chart<'a>              | ✔️     |   -     | -         | -  | ✔️     | -    |
| Clear                  | ✔️     |   -     | -         | -  | ✔️     | -    |
| Gauge<'a>              | ✔️     |   -     | -         | -  | ✔️     | -    |
| LineGauge<'a>          | -     |   -     | -         | -  | -     | -    |
| ListState              | ✔️     | ✔️     | -         | -  | ✔️     | -    |
| ListItem<'a>           | ✔️     |   -     | ✔️       | ✔️  | ✔️     | -    |
| List<'a>               | ✔️     |   -     | -         | -  | ✔️     | -    |
| Paragraph<'a>          | ✔️     |   -     | -         | -  | ✔️     | -    |
| Wrap                   | ✔️     |   -     | -         | -  | ✔️     | ✔️   |
| WordWrapper<'a, O, I>  | -     |   -     | -         | -  | -     | -    |
| LineTruncator<'a, O, I>| -     |   -     | -         | -  | -     | -    |
| Set                    | ✔️     |   -     | -         | -  | ✔️     | -    |
| ScrollbarState         | ✔️     | ✔️     | -         | -  | ✔️     | -    |
| Scrollbar<'a>          | ✔️     |   -     | -         | -  | ✔️     | -    |
| Sparkline<'a>          | ✔️     |   -     | -         | -  | ✔️     | -    |
| Cell<'a>               | ✔️     | ✔️     | ✔️       | ✔️  | ✔️     | -    |
| Row<'a>                | ✔️     | ✔️     | ✔️       | ✔️  | ✔️     | -    |
| Table<'a>              | ✔️     |   -     | ✔️       | ✔️  | ✔️     | -    |
| TableState             | ✔️     | ✔️     | -         | -  | ✔️     | -    |
| Tabs<'a>               | ✔️     |   -     | -         | -  | ✔️     | -    |

**Comment by joshka** [comment]
Sure thing - that might be preferable - Perhaps a module at a time so as not to make too many PRs.
Most of these should be derived implementations.
Perhaps make a quick checklist comment in this issue and update it with progress?

**Comment by TieWay59** [comment]
Hi @joshka, I'm back from my summer school homework. I read your reviews carefully and I learn that I have done some bad practice in the last WIP PR. Here is my latest idea about this task:

1. How to split it up?
   - I've learned the lesson that adding traits won't be so easy like adding simple text in some derived brackets. So I think we should focus on one or two traits in one PR, this can reduce much burden of review and context-shifting discussion. 
   - > Note my comment about ordering. Of these, I'd probably say that Debug and Default are the two most important, followed by Clone and Copy. Being able to glance at a derives list and see that these are implemented is something I personally often rely on.
   - I agree, so I suppose we can split this task into:
   - [ ] `Debug and Default`,
   - [ ] `Clone and Copy`: Copy is not very recommended for complicated structs, this needs discussion.
   - [ ] `Hash`: f64 can't be hash by default, so this would need more discussion.
   - [ ] `Eq, PartialEq, Ord, PartialOrd`: may be small cuz not widely needed
   - [ ] `Display`: The display pattern would be way too long to discuss&review.
2. How to order traits?
   - > Perhaps use the following order: Debug, Default, Clone, Copy, Eq, PartialEq, Ord, PartialOrd, Hash.
   - Since rust-fmt won't provide auto-mated style guild (https://github.com/rust-lang/style-team/issues/154) I agree with your suggestion, and I'll keep following this order in the future.
3. What's next?
   - I'll change https://github.com/ratatui-org/ratatui/pull/339 into a simpler one focusing on `Debug and Default`.

**Comment by TieWay59** [comment]
## Tracker

   - [x] `Debug and Default`: https://github.com/ratatui-org/ratatui/pull/339
   - [ ] `Clone and Copy`:  
   - [ ] `Hash`:  
   - [ ] `Eq, PartialEq, Ord, PartialOrd`:  
   - [ ] `Display`:

**Comment by TieWay59** [comment]
I've been stuck on this `Box<dyn Grid>` many times, it's the only one that we can not attach any other common trait on it. I'd like to pick it up for more ideas, how should we handle it? @joshka 

https://github.com/ratatui-org/ratatui/blob/bf4944683d6afb6f42bec80a1bd308ecdac50cbc/src/widgets/canvas/mod.rs#L179-L183

https://github.com/ratatui-org/ratatui/blob/bf4944683d6afb6f42bec80a1bd308ecdac50cbc/src/widgets/canvas/mod.rs#L248-L258

https://github.com/ratatui-org/ratatui/blob/bf4944683d6afb6f42bec80a1bd308ecdac50cbc/src/widgets/canvas/mod.rs#L45-L52

**Comment by joshka** [comment]
> I've been stuck on this `Box<dyn Grid>` many times, it's the only one that we can not attach any other common trait on it. I'd like to pick it up for more ideas, how should we handle it? @joshka

I'm not sure TBH. I'm fine with leaving this and implementing it when someone needs it.

**Comment by TieWay59** [comment]
@joshka, I'm SORRY I've been away from GitHub due to a difficult personal issue. I'm glad to know this issue has been closed after so much work of collaboration, It's so nice to work with you in Ratatui, thank you for all of your advice and quick reply!
