### ISSUE TITLE
Rename the organization name to "ratatui" or something else

### ISSUE THREAD

**Issue by appsubscribe** [ratatui-org/ratatui#319]
## Problem
This is not really a problem. But whenever I look into this repo and saw "`tui-rs-revival`" org name it feels something not authentic. Since the current team has done an amazing jobs in pushing new features and fixing bugs. I think it deserves its own org name instead of referring to old repo `tui-rs`.

## Solution

The team should decide a new name e.g. `ratatui`, `ratatui-rs`, etc.

## Alternatives
N/A

## Additional context
Just my little opinion. You guys are amazing!

**Comment by lthoerner** [comment]
I very much agree. It feels a little weird to me to have the username be descriptive of the project rather than just a normal username.

**Comment by joshka** [comment]
I feel similarly. To me the name looks backward to where we came from rather than forward to where we aim to be.
https://github.com/ratatui is taken by a user already and github doesn't allow users and orgs to be named the same.

**Comment by rezigned** [comment]
> I feel similarly. To me the name looks backward to where we came from rather than forward to where we aim to be. https://github.com/ratatui is taken by a user already and github doesn't allow users and orgs to be named the same.

Maybe `ratatui-rs`? or other name.

**Comment by rezigned** [comment]
FYI: I just reserved https://github.com/ratatui-rs org name (just to prevent someone take over). I'll transfer 100% ownership to the current team owner if you want to use this org name. Please let me know 👍

**Comment by mindoodoo** [comment]
Yup +1 on getting a better name in. `tui-rs-revival` was when we were only a handful of people just getting started, but makes sense to change it !

@rezigned thanks for reserving the name, we'll get back to you soon !

**Comment by orhun** [comment]
I already reached out to the user "ratatui" a couple of months ago about this. Didn't hear back from them yet.

**Comment by mindoodoo** [comment]
@orhun Maybe worth one last shot ?

**Comment by orhun** [comment]
Sure, let me ping him again. If he doesn't reply shortly, I think we can simply switch to @ratatui-rs

**Comment by rezigned** [comment]
I just invited @orhun as owner. You can remove me when everything is done. From my exp. It's hard to get existing user to give up their handle especially if they already have some repos in there.

![image](https://github.com/tui-rs-revival/ratatui/assets/562145/6f6b2cc6-9cd5-4180-a924-fb3f88d4a74e)

**Comment by a-kenji** [comment]
I think `ratatui-rs` is already an improvement, but would prefer `ratatui-org` personally as a name for the organisation.

**Comment by orhun** [comment]
Thank you @rezigned for the invite! Let's wait for a bit for @ratatui's response and also consider our other options.

> I think ratatui-rs is already an improvement, but would prefer ratatui-org personally as a name for the organisation.

Hmm, this is a fair point. (thinking about @zellij-org)

**Comment by samyosm** [comment]
@Ratatui would seem to be inactive since 2013, surely he is violating [GitHub's Name Squatting Policy](https://docs.github.com/en/site-policy/other-site-policies/github-username-policy#name-squatting-policy). We might have better chances to the name by asking GitHub directly.

**Comment by orhun** [comment]
Sadly, GitHub does not release the squatting usernames anymore.

We now have @ratatui-org and I propose we switch to it as soon as possible if there are no objections.
