### ISSUE TITLE
BarChart: horizontal bars

### ISSUE THREAD

**Issue by karthago1** [ratatui-org/ratatui#321]
## Problem
If we want to show the value in the bars, we need to set the bar width as wide as the value text. Hence we can't use the available space in an efficient manner. 

## Solution
1. Print the value vertically. I made a lot of research. I think it is not possible to print the numbers vertically and 90° rotated. (or is it possible?)
2. Print the Bars horizontally instead of vertically. 
I am still playing with this idea. all we need is a new API function `horizontal_bars(true)`
I need to integrate this in our application and get some feedback first. but the horizontal bars looks weird to me, but equally functional. I don't know what is your opinion.

![barchart](https://github.com/tui-rs-revival/ratatui/assets/15311024/d906a9d5-2fe9-484b-b7ac-edba4c33ab05)

**Comment by mindoodoo** [comment]
Could you elaborate a little bit on what feels weird about this approach ?

In general I think a horizontal barchart feature would be a great addition to the crate ! Looking forward to other peoples thoughts on this !

**Comment by karthago1** [comment]
No It is just that I am used to vertical bars. but in maybe in this case horizontal bars are more compact.

I don't know, if someone tried to print text vertically with rotated characters. I couldn't find a way to do it.
