### ISSUE TITLE
Input gets duplicated (event fires twice)

### ISSUE THREAD

**Issue by dev-ardi** [ratatui-org/ratatui#347]
## Description

When I type any keyboard input the event fires twice: Once on press and once on release.

https://github.com/ratatui-org/ratatui/assets/47633543/721bc59b-2448-4774-b157-8c2b6054ff9d

## To Reproduce

https://github.com/fdehau/tui-rs/blob/master/examples/user_input.rs

## Environment

- OS: Windows
- Terminal Emulator: conhost, alacritty
- Crate version: ratatui = "0.22.0"
- Backend: crossterm

## Additional context

It works for some reason in another project where it was failing until I refactored the display logic to another function

**Comment by joshka** [comment]
Hi there. This has come up a few times. See https://docs.rs/crossterm/latest/crossterm/event/struct.KeyEvent.html
To fix this, check `KeyEvent.kind == KeyEventKind.Press` (on windows).

That's a probably a difficult one as ratatui doesn't have any code to handle keyboard input (other than our examples). Can you help us out (and perhaps the next person who hits this) by noting where in the docs you looked for this and didn't find enough info?

**Comment by dev-ardi** [comment]
Honestly the only docs I read were the readme.md and the examples, and also the relevant data structures and methods that I used.

But the examples are wrong on windows though!

**Comment by mindoodoo** [comment]
> But the examples are wrong on windows though!

Could you elaborate on why they are wrong ?

**Comment by dev-ardi** [comment]
Well the expected behaviour would be that the down key only moves down by one but it moves down by two!

**Comment by dev-ardi** [comment]
Yes
