### ISSUE TITLE
Buffer: Use compact_str or similar in buffer::Cell

### ISSUE THREAD

**Issue by jamespharaoh** [ratatui-org/ratatui#356]
## Problem

Every Cell, ie every character on the screen, potentially allocates a String. This is rather inefficient in terms of memory.

## Solution

Using `compact_str` instead of `String` uses exactly the same space in the cell, but it will store the data inline in the vast majority of cases. This crate can store up to 24 bytes (12 on 32-bit) which should rarely if ever be exceeded. There's no problem if it is exceeded, because it will switch to allocation automatically.

## Alternatives

- There are countless other crates offering similar features, for example: `arrayvec`, `flexstr`, `kstring`, `smartstring`, `smol_str`.

## Additional context

I'm planning to attempt to implement this myself, but I'd appreciate any thoughts or comments from the community.

Optionally this could be behind a feature flag, although I don't see any reason not to make it the default.

**Comment by joshka** [comment]
Is this solving a measured or perceived issue or a hypothetical one?

Can you quantify the worst case memory / cpu usage and impact this change should achieve for the largest possible screen (256x256). 

I'm guessing that 64KiB at modern ram speeds (~20-30GB/s) is probably insignificant (~3 microseconds). A display running at 60fps has 16667 microseconds to render a frame (so we're talking about optimizing something that has a duty cycle of 0.02%. These are SWAGs (scientific wild ass guesses), but probably are a good starting point. I'd be curious to see how wrong they are though.

There's probably some order of magnitude differences I haven't factored in. If you're in one of those fun situations where those are key to your environment, I'd love to hear more.

**Comment by joshka** [comment]
Also take note of https://github.com/ratatui-org/ratatui/pull/231

**Comment by jamespharaoh** [comment]
As per the glibc docs the default allocation size for the standard allocator is four pointers, so 32 bytes on a 64-bit system. I am not sure about other platforms. Docs here:

https://sourceware.org/glibc/wiki/MallocInternals

So a string with allocated capacity will use at least 32 bytes on 64-bit. Ratatui has a double buffer, so we end up with 64 bytes per screen cell, which can easily be measured in megabytes for a large terminal with a small font.

This seems unreasonable to me for a CLI app, if it is simple to avoid. Maybe I'm running in a memory-restricted environment, eg a small virtual machine which I am accessing via SSH from a machine with a large screen. Maybe I'm running a few apps in different windows.

As for performance overhead, I'll come back to you on that.

**Comment by joshka** [comment]
To hit the absolute worst case, you'd have an 8K screen, running with a ~10 point font (or equivalent smaller fonts on smaller screens), and that would hit: 32*2*u16:max = 4MB. Even using Apple's fairly expensive prices for RAM that's about 5 cents worth (32GB = $400, 4MB = $0.05). I think it's reasonable to not optimize for RAM usage unless there are other benefits that can be measured.

Probably something that would be worth doing for this though eventually might be identifying the places where we don't actually have to split up the graphemes to individual cells, and splat an entire string to the line at once instead of cell by cell.

**Comment by Valentin271** [comment]
Closing because https://github.com/ratatui-org/ratatui/pull/601, using `compact_str`, has been merged.
