### ISSUE TITLE
Table: Add option to make `expand_to_fill` configurable for `Table::widths`

### ISSUE THREAD

**Issue by hasezoey** [ratatui-org/ratatui#370]
## Problem
Currently on widget `Table` (`widgets/table.rs`), all `.widths` are thrown into a `Layout` (like the user would do for a block), but with the added (currently non-configurable) `expand_to_fill` set to `false`, making all Constraints other than Percentage use only the minimal amount

## Solution
Add option to have `widths` `expand_to_fill` configurable, maybe something like `widths_expand_to_fill()`

## Alternatives
also a alternative would be to just remove the `expand_to_fill` call

## Additional context
Currently if any other constraint than `Percentage` is used, the columns will always use the minimal amount of width, example:

```rust
// testing backend for consistent size and printing to console
let backend = TestBackend::new(116, 27);

// widths as applied to the table
.widths(&[
    Constraint::Length(4),
    Constraint::Max(30),
    Constraint::Min(10),
    Constraint::Max(4),
]);

// debug print in table.rs get_columns_widths
println!("max_width {}, chunks: {:#?}", max_width, chunks.iter().map(|v| v.width).collect::<Vec<u16>>());
```

would result in:

```
max_width 114, chunks: [
    4,
    1, // spacer
    30,
    1, // spacer
    10,
    1, // spacer
    4,
]
```

whereas changing `expand_to_fill` to `true` would result in:

```
max_width 114, chunks: [
    4,
    1, // spacer
    30,
    1, // spacer
    73,
    1, // spacer
    4,
]
```

**Comment by hasezoey** [comment]
i dont know if this is actually a proper solution (exposing `expand_to_fill`), because if there are multiple elements that could grow, only one gets grown (as per cassowary documentation)

> Due to the nature of the algorithm, "in-between" solutions, although just as valid, are not picked.

i may also just completely misunderstand this though

**Comment by hasezoey** [comment]
this may be (at least partially) fixed by #395

**Comment by joshka** [comment]
I've been thinking a bit about this specific issue also over the last couple of days from the perspective of `Layout` though. I suspect that the rationale for keeping the method private was that there's a few different ways that making things fit right could be achieved, and it's difficult to make that stable.

I think this idea is fine, but it's worth pausing for a little while to let it bubble together with the other things we're playing with around layout. Do you have a specific use case for this, or is it more about removing a limitation?

**Comment by hasezoey** [comment]
> Do you have a specific use case for this, or is it more about removing a limitation?

my use-case is / was that i wanted the table's columns to be able to use the full area, instead of just the minimal amount the columns need, example given was that the following should take the full `116` space, instead of just `51` minimal space:

```rust
.widths(&[
    Constraint::Length(4),
    Constraint::Max(30),
    Constraint::Min(10),
    Constraint::Max(4),
]);
```

but i later noticed that just enabling `expand_to_fill` would only increase one element to use the remaining amount, instead of splitting it across all possible constraints

a example of that (with multiple expandable constraints) would be along the lines of:

```rust
.widths(&[
    Constraint::Length(4),
    Constraint::Max(30),
    Constraint::Min(10),
    Constraint::Max(4),
    Constraint::Min(10),
]);
```

would currently resulting:

```text
max_width 116, chunks: [
    0, // selection column
    4,
    1, // spacer
    30,
    1, // spacer
    10,
    1, // spacer
    4,
    1, // spacer
    10,
]
```
(combined length is `62`)

but using `expand_to_fill` in this example would result in just one of the `Min` constraints to be fill fully, that is also why i mentioned #395 that may possibly (at least partially) fix this

result of `expand_to_fill` set to `true`:
```rust
max_width 116, chunks: [
    0,
    4,
    1,
    30,
    1,
    10,
    1,
    4,
    1,
    64,
]
```
(only the last element gets increased, instead of being split across the growable elements)

**Comment by hasezoey** [comment]
i also just quickly applied the same code with #395, which currently results in the following

`expand_to_fill` set to `false`:

```txt
max_width 116, chunks: [
    0,
    4,
    1,
    1,
    1,
    10,
    1,
    1,
    1,
    10,
]
```
(combined length `30`)

`expand_to_fill` set to `true`:

```txt
max_width 116, chunks: [
    0,
    4,
    0,
    29,
    1,
    37,
    1,
    4,
    1,
    38,
]
```
(combined length `115`)

this last result looks way better to me, but the first spacer is somehow `0`, i think this would need to be fixed
