### ISSUE TITLE
Move all demo gifs to github

### ISSUE THREAD

**Issue by kdheepak** [ratatui-org/ratatui#401]
## Problem

Currently a lot of the demo gifs are on vhs's website. For reliability, we might want to consider moving them to github. 

## Solution

We don't want to bloat the repo git history. So we can either:

1. Upload gifs to a separate git repo
2. Upload gifs to a gist in a comment or in a README.md file
3. Upload gifs to a release

**Comment by hasezoey** [comment]
also consider using [git lfs](https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage)

**Comment by joshka** [comment]
> also consider using [git lfs](https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage)

Good idea, but we might hit quotas pretty quickly with that:

Demo.gif is 2.8MB, the monthly quota on github's lfs is just 1GiB, and the readme was visited 5475 times in the last 2 weeks (e.g. 15.3GB just for that image), VHS also supports mp4 (651KB->3.6GB), and webm (846KB->4.6GB). I'm unsure how those would render on crates.io, but they look ok on Github. E.g.:

https://github.com/ratatui-org/ratatui/assets/381361/1df72b8c-c202-443c-b718-71b25b0b462f

https://github.com/ratatui-org/ratatui/assets/381361/c625279c-0787-43fc-8549-36bc902602f0

**Comment by joshka** [comment]
+1 to the idea. I'd like this to be easy to automate both in CI and locally.

**Comment by orhun** [comment]
Yeah we totally need this...

**Comment by joshka** [comment]
I took the approach of creating a new branch to store the gifs. https://github.com/ratatui-org/ratatui/tree/images

**Comment by joshka** [comment]
Done
