### ISSUE TITLE
Scrollbar without arrows

### ISSUE THREAD

**Issue by fritzrehde** [ratatui-org/ratatui#413]
## Description

I am not sure if this is the expected behaviour of the Scrollbar feature, so I'm asking here.
I know that the Scrollbar features arrows by default at the moment, but I would like to remove them.
Therefore, I have the following code:
```
        frame.render_stateful_widget(
            Scrollbar::default()
                .orientation(ScrollbarOrientation::VerticalRight)
                .begin_symbol(None)
                .end_symbol(None),
            area,
            &mut self.help_menu.vertical_scroll_state,
        );
```
However, this produces:
```
┌help────────────────────█
│                        █
│                        ║
│                        ║
└────────────────────────║
```
The issue here is that the scrollbar also takes up the corners of the block's borders. I would prefer to have normal corners, and the scrollbar take up everything besides the corners. I read through the #228 and saw this exact issue was mentioned somewhere and temporarily implemented with `.arrows(None)` or similar, but that was later removed.
My question: Is there a way to achieve my desired functionality?

## To Reproduce

The code I wrote above.

## Expected behavior

Achieving this somehow:
```
┌help────────────────────┐
│                        █
│                        ║
│                        ║
└────────────────────────┘
```

## Environment

- OS: Arch Linux
- Terminal Emulator: Alacritty
- Font: -
- Crate version: 0.22.0
- Backend: crossterm

**Comment by joshka** [comment]
I think this may be as simple as rendering the scrollbar into the area that doesn't include the corners (i.e. `Rect { y: area.y+1, height: area.height - 2, ..area }` (and turning off the arrows like you have already).

P.S. just a heads up that there's a small breaking change in the next release in https://github.com/ratatui-org/ratatui/pull/330. It's available in the alpha release if you want to test your code early.

**Comment by kdheepak** [comment]
Using a vertical `Margin` of `1` will do the trick:

```diff
        frame.render_stateful_widget(
            Scrollbar::default()
                .orientation(ScrollbarOrientation::VerticalRight)
                .begin_symbol(None)
                .end_symbol(None),
-            area,
+            area.inner(&Margin {vertical: 1, horizontal: 0}),
            &mut self.help_menu.vertical_scroll_state,
        );
```

**Comment by fritzrehde** [comment]
Ok, that makes sense. One more question regarding margins: I have this rendering code:
```
    pub fn render<B: Backend>(&mut self, frame: &mut Frame<B>) {
        if self.is_shown {
            let area = centered_rect(50, 50, frame.size());

            let text: Text = self.body.as_str().into();

            // Render the paragraph with the updated scroll state
            let paragraph = Paragraph::new(text)
                .block(Block::default().title("help").borders(Borders::ALL))
                .alignment(Alignment::Left)
                .wrap(Wrap { trim: true })
                // scroll offset for each axis: (y, x)
                .scroll((self.vertical_scroll_index as u16, 0));

            frame.render_widget(
                paragraph,
                area.inner(&Margin {
                    vertical: 0,
                    horizontal: 1,
                }),
            );

            // Render the scrollbar next to the paragraph
            frame.render_stateful_widget(
                Scrollbar::default()
                    .orientation(ScrollbarOrientation::VerticalRight)
                    .begin_symbol(None)
                    .end_symbol(None),
                area.inner(&Margin {
                    vertical: 1,
                    horizontal: 0,
                }),
                &mut self.vertical_scroll_state,
            );
        }
    }
    ```
My assumption here is that the paragraph widget is somehow "inside" the scrollbar widget, so setting the horizontal margin of the paragraph (help menu body) to 1 would only affect that paragraph inside the widet, but it doesn't. 
What I want is to have one free vertical between the widget outline and the widget body content (paragraph), ideally on the left and the right, how can i do this? What happens now is that the scrollbar is pushed out of the widget completely, so one pixel to the right of the widget.

**Comment by kdheepak** [comment]
If I'm understanding your question, this is what you want:

```diff
    pub fn render<B: Backend>(&mut self, frame: &mut Frame<B>) {
        if self.is_shown {
            let area = centered_rect(50, 50, frame.size());

            let text: Text = self.body.as_str().into();

            // Render the paragraph with the updated scroll state
            let paragraph = Paragraph::new(text)
                .block(Block::default().title("help").borders(Borders::ALL))
                .alignment(Alignment::Left)
                .wrap(Wrap { trim: true })
                // scroll offset for each axis: (y, x)
                .scroll((self.vertical_scroll_index as u16, 0));

            frame.render_widget(
                paragraph,
+                area,
-                area.inner(&Margin {
-                    vertical: 0,
-                    horizontal: 1,
-                }),
            );

            // Render the scrollbar next to the paragraph
            frame.render_stateful_widget(
                Scrollbar::default()
                    .orientation(ScrollbarOrientation::VerticalRight)
                    .begin_symbol(None)
                    .end_symbol(None),
                area.inner(&Margin {
                    vertical: 1,
                    horizontal: 0,
                }),
                &mut self.vertical_scroll_state,
            );
        }
    }
```

`Paragraph` with a `Block` with borders will add a margin already for the borders, so you don't need to add one again.

**Comment by joshka** [comment]
Use Padding to add space within a block.

```rust
frame.render_widget(
  Paragraph::new(text)
    .block(Block::new()
      .padding(Padding { left:1, right: 1, top:0, bottom:0 }) // (or Padding::new(1,1,0,0)
      .borders(Borders::ALL)),
  area);
frame.render_stateful_widget(ScrollBar::new()..., area);
```

The Paragraph is not really within the scrollbar. The Paragraph draws a block, then draws its text within the block. The ScrollBar is then drawn over the existing block.

Because the ScrollBar just draws over the cells where it needs to (and not the entire area, you can often just use the same area as the outer block.

Closing this out as I think it's been solved.
