### ISSUE TITLE
LineGauge: gauge_style is confusing

### ISSUE THREAD

**Issue by Fabus1184** [ratatui-org/ratatui#424]
Right now the LineGauge::gauge_style.**bg** is actually applied to the **foreground** of the filled part of the line.

This is rather confusing, I would suggest using two different styles (e.g. filled_style, empty_style) for the two parts. This also enables to use different background colors, which are currently always None.

https://github.com/ratatui-org/ratatui/blob/61533712be57f3921217a905618b319975f90330/src/widgets/gauge.rs#L276-L287

**Comment by joshka** [comment]
@Fabus1184 Thanks. I think I agree on this idea. We'd need to keep in mind older apps for this and maintain compatibility, but it's a reasonable request.

**Comment by nowNick** [comment]
Hi all!

I wanted to start contributing to this repo and I opened up a PR that I think solves this issue. I'd love to hear your feedback 😊

**Comment by nowNick** [comment]
Hi @TieWay59 , You can find a screenshot in my PR or would you like to see some other screenshot? Please note that it's still a _"work in progress"_

**Comment by TieWay59** [comment]
This issue is solved by #565. @Fabus1184 do you feel ready to close it or is something still not implemented?
