### ISSUE TITLE
Braille symbol not displayed

### ISSUE THREAD

**Issue by relf** [ratatui-org/ratatui#457]
## Description
The Braille symbol is not displayed on my Windows 10 machine (replaced by a framed question mark character).
See screenshot below.

## To Reproduce

In Windows cmd, after cloning the repo:
```
cargo run --example=chart --features=crossterm
```

## Expected behavior

See [chart example](https://github.com/ratatui-org/ratatui/blob/main/examples/README.md#chart-chartrs)

## Screenshots

![ratatui_bug](https://github.com/ratatui-org/ratatui/assets/1198802/7ae6f31b-8eb4-4c66-b13b-1c94641196d7)

## Environment

- OS: Windows 10
- Terminal Emulator: cmd
- Font: Consolas, but I've tried some others (Courrier New, Lucida Console, ...) without success. Is there a recommended font?  
- Crate version: 0.23.0
- Backend: crossterm

**Comment by Valentin271** [comment]
Have you tried powershell and/or in WSL? (will probably be the same result but still good to know)

Either way I found a [similar issue on gtop](https://github.com/aksakalli/gtop/issues/21) with a fix.
See also the [accepted answer on this StackOverflow post](https://stackoverflow.com/questions/33520197/print-braille-characters-to-cmd-c).

It seems like this is a font issue, so if you want a specific font, it may be worth to try a [Nerd Font](https://www.nerdfonts.com/).

_Disclaimer: I did not test any of these._

**Comment by relf** [comment]
Thanks for the swift reply. I confirm it does not work with powershell nor in WSL.
I have to test but your links seem to give a solution. Too bad the Windows default font does not make it!

I do not know if I am the only user on Windows here 😅 but it might be worth to add a warning in the doc, an information about the font requirement could be added.

**Comment by relf** [comment]
Ok, I confirm that it works once the Iosevka font is installed as described in the [first link](https://github.com/aksakalli/gtop/issues/21) mentionned above. 
In my case (weirdly?) I did not have to edit the registry, the font was available in the cmd properties just after the font installation (it was lucky because I do not have the admin rights to play with regedit). Once selected it becomes the default for subsequent cmd.
The second font mentioned in the stackoverflow link does not work for me. And finally I've also tried a Nerd Font font without any success as well.

I do not close the issue in case you want to keep it around at least till the font info is added somewhere in the doc, otherwise feel free to close it.

**Comment by joshka** [comment]
A quick google to see if there's a good list of which fonts support braille character block I found:
https://www.fileformat.info/info/unicode/block/braille_patterns/fontsupport.htm

There's probably some way to download a large amount of fonts and detect whether each supports braille (perhaps using Homebrew's [font tap](https://github.com/Homebrew/homebrew-cask-fonts) and then slapping something together with fontconfig (https://crates.io/search?q=fontconfig).

I'd suggest for now, we add a note in the Braille invariant as you mentioned.

**Comment by joshka** [comment]
Closing and opening #509
