### ISSUE TITLE
Use new module name convention (`src/xxx.rs` instead of `src/xxx/mod.rs`)

### ISSUE THREAD

**Issue by joshka** [ratatui-org/ratatui#488]
## Problem
Navigating to module source files named `xxx/mod.rs` is a regular paper cut annoyance as the files in the `tests`, `examples`, and `benches` directories with the same name generally have higher precedence.

## Solution

```shell
mv src/backend/mod.rs src/backend.rs
mv src/text/mod.rs src/text.rs
mv src/widgets/barchart/mod.rs src/barchart.rs
mv src/widgets/canvas/mod.rs src/canvas.rs
mv src/widgets/mod.rs src/widgets.rs
```

## Alternatives
Perhaps there's a way to ensure that VSCode lists modules first?

## Additional context
<img width="602" alt="image" src="https://github.com/ratatui-org/ratatui/assets/381361/6cdb42b3-1206-4699-becf-b7b1a7b17500">

**Comment by kdheepak** [comment]
I'm not so sure how I feel about this.

1. I do understand the pain point, but seems like it is a VSCode specific optimization. For example,

in neovim with telescope:

<img width="1512" alt="image" src="https://github.com/ratatui-org/ratatui/assets/1813121/38b1d0ef-99b8-475f-b067-f49fe09d2ebd">

in terminal with fzf:

<img width="1512" alt="image" src="https://github.com/ratatui-org/ratatui/assets/1813121/7c37fa6c-c5b0-47ee-9ba5-acd9fe5129f0">

2. I have a feeling that this breaks the convention that rust developers might expect. I personally would like to look at more rust crates to see what people are doing. If there's a programmatic way to get statistics that would be awesome, and would motivate this change more strongly for me.

3. Currently, someone new to rust or new to ratatui will be able to see that all "widgets" related code is in "./src/widgets", and similar for the other modules. In my opinion the new version is less intuitive.

4. VSCode uses fuzzy find. It can actually be faster to get to the `mod.rs` files the way it is right now:

<img width="620" alt="image" src="https://github.com/ratatui-org/ratatui/assets/1813121/27d7fe27-3b14-4de2-8225-15334617aeb4">

**Comment by joshka** [comment]
I know that there are ways to avoid this with fuzzy find, but the issue is that there are two types of modules - those with submodules and those without. In the `mod.rs` world, I regularly have to remember which, and then actively choose a different action because of the difference. But that difference has no meaningful value to me.

Would looking to https://doc.rust-lang.org/book/ch07-02-defining-modules-to-control-scope-and-privacy.html for some guidance on expectations help? (`mod.rs` only appears in the book only 6 time in 2 paragraphs - both times as a secondary alternative, not the primary). The purpose of the introduction of named module files instead of mod.rs was to avoid a whole bunch of files that are all named the same (i.e. to avoid this particular paper cut).

**Comment by kdheepak** [comment]
The only disadvantage that I find with this approach is that with terminal tab complete `vim ./src/widg<TAB>` completes to `vim ./src/widgets` instead of `vim ./src/widgets/`. The former in bash is more annoying for users, because they have to `<TAB>` twice to then see that there's a `.rs` / a folder and type `/` and then continue tabbing to autocomplete to the file; although in zsh and fish it is not as annoying.
