### ISSUE TITLE
Layout: Configure padding / gaps between areas in layouts

### ISSUE THREAD

**Issue by joshka** [ratatui-org/ratatui#497]
## Problem
Often I want an empty space (row or column) in between areas. Usually these are the same width or height.
The way to do this currently is to add a `Constraint::Length(1)` between each of the other constraints and then go and bump every index up by the amount that this shifts the output array. E.g.:
```rust
Paragraph::new("foo").render(areas[0], buf);
Paragraph::new("bar").render(areas[2], buf); // etc.
```
It would be nice if instead we could ignore these gaps.

- [ ] I'm not sure what the best name for this is (padding / gap / other?)
- [ ] I'm not sure if we should support different gaps between elements (i.e. a constraint that is a gap constraint) or just a single gap amount for the entire layout (I'd like to hear other people's perspective on this before anyone implements this)

## Solution
The simplest solution is to add
```rust
gap: u16,
```
and the appropriate builder method (`fn gap()`)
and then factor that into the distance between the end and start of areas:
https://github.com/ratatui-org/ratatui/blob/a7bf4b3f36f3281017d112ac1a67af7e82308261/src/layout.rs#L561-L564

## Alternatives
A more advanced option would add an extra variant to `Constraint` that inserts an ignored gap (I'm unsure how complex we'd want to go for this, but this might be useful for more complex layouts.

## Additional context
This would probably simplify some of the rendering logic in Table.

**Comment by Valentin271** [comment]
I think this can be closed after #821. They might be some other cases:

- different spacing size for each space
- space around areas

But we may create more specific issues for these if it turns out we need it.
