### ISSUE TITLE
Gauge: renders percentage inverted since ratatui 0.22.0

### ISSUE THREAD

**Issue by LeoniePhiline** [ratatui-org/ratatui#501]
## Description

In ratatui 0.21.0, a full gauge is rendered correctly:
![ratatui-0 21 0](https://github.com/ratatui-org/ratatui/assets/22329650/1f7cffc1-7682-4058-9d0a-13e438ac1016)

However, in ratatui 0.22.0 and 0.23.0, a full gauge is rendered with inverted fg/bg at the percentage label part:
![ratatui-0 22 0](https://github.com/ratatui-org/ratatui/assets/22329650/99258c74-935b-4524-ac28-5d1b8f39fb60)

[Diff v0.21.0...v0.22.0](https://github.com/ratatui-org/ratatui/compare/v0.21.0...v0.22.0#diff-f154dfc8f60440dd00333e94b2b925d6701dac0c874ae7cad6be32440ba5ab4e)

## To Reproduce

Render a gauge (with crossterm) with ratatui 0.21.0, then with 0.22.0+.

Example:

```rust
let gauge = Gauge::default()
    .gauge_style(
        Style::default()
            .fg(Color::LightGreen)
            .add_modifier(Modifier::BOLD)
    )
    .use_unicode(true)
    .ratio(100.0);
```

## Expected behavior

"100%" Percentage label being rendered with gauge color as background.

## Screenshots

See above.

## Environment

- OS: OpenSUSE Tumbleweed
- Terminal Emulator: Konsole
- Font: Hasklug Nerd Font Mono
- Crate version: 0.21, 0.22 and 0.33
- Backend: crossterm 0.26.1 / 0.27.0

## Additional context

*None*

**Comment by joshka** [comment]
I recall writing that code to fix some rendering issues with VHS a while back. I'll fix it back soon.
