### ISSUE TITLE
[fuzz-test] Arithmetic overflow occurs while using API Constraint::apply()

### ISSUE THREAD

**Issue by HeeillWang** [ratatui-org/ratatui#522]
## Description

I executed fuzzing to test tui-0.19.0 APIs. This reproduced on ratatui as well. I guess other variants of `Constraint` may overflow as well...

~~~
impl Constraint {
    pub fn apply(&self, length: u16) -> u16 {
        match *self {
            Constraint::Percentage(p) => length * p / 100,
            Constraint::Ratio(num, den) => {
                let r = num * u32::from(length) / den;   // overflow!
                r as u16
            }

~~~

## To Reproduce

~~~
let mut self_obj  = Constraint::Ratio(fuzz_arg0, fuzz_arg1);
self_obj.apply(fuzz_arg2);
~~~

fuzz input : `(589505315, 302, 8995)`

## Expected behavior

Adding assert statement or just explicitly mention panic condition on API doc

**Comment by joshka** [comment]
This does not apply to Ratatui.
https://github.com/ratatui-org/ratatui/blob/8135030c748bc386f723d599e67c348fa766870e/src/layout.rs#L125-L131
