### ISSUE TITLE
Corner borders for block

### ISSUE THREAD

**Issue by kdheepak** [ratatui-org/ratatui#528]
## Problem

Right now, `Border` supports the following:

```rust
/// Show no border (default)
const NONE   = 0b0000;
/// Show the top border
const TOP    = 0b0001;
/// Show the right border
const RIGHT  = 0b0010;
/// Show the bottom border
const BOTTOM = 0b0100;
/// Show the left border
const LEFT   = 0b1000;
/// Show all borders
const ALL = Self::TOP.bits() | Self::RIGHT.bits() | Self::BOTTOM.bits() | Self::LEFT.bits();
```

But I'd like to only draw corners, e.g.:

```
 ┌         ┐
  
    hello     
           
 └         ┘
```

What would be the best way to implement this?

**Comment by joshka** [comment]
I was thinking about something similar the other day (I wanted custom borders). Some of the other types create a `symbol::x::Set` type for the various values. We need one for Borders too. I'll put together a PR for the code I have lying around that does this in a moment.
