### ISSUE TITLE
Layout: Rename `segment_size` in `Layout` and make it public

### ISSUE THREAD

**Issue by kdheepak** [ratatui-org/ratatui#536]
## Problem

Currently `segment_size` is only available to use internally. I think we should make it public:

```rust
// without segment_size

let target = Rect {
    x: 0,
    y: 0,
    width: 10,
    height: 1,
};

let chunks = Layout::default()
    .direction(Direction::Horizontal)
    .constraints([Constraint::Min(0), Constraint::Min(0)].as_ref())
    .split(target);

dbg!(chunks);

// [src/layout.rs:764] chunks = [
//     Rect {
//         x: 0,
//         y: 0,
//         width: 0,
//         height: 1,
//     },
//     Rect {
//         x: 0,
//         y: 0,
//         width: 10,
//         height: 1,
//     },
// ]

// With segment_size

let target = Rect {
    x: 0,
    y: 0,
    width: 10,
    height: 1,
};

let chunks = Layout::default()
    .direction(Direction::Horizontal)
    .constraints([Constraint::Min(0), Constraint::Min(0)].as_ref())
    .segment_size(SegmentSize::EvenDistribution)
    .split(target);

dbg!(chunks);

// [src/layout.rs:764] chunks = [
//     Rect {
//         x: 0,
//         y: 0,
//         width: 5,
//         height: 1,
//     },
//     Rect {
//         x: 5,
//         y: 0,
//         width: 5,
//         height: 1,
//     },
// ]

```

## Additional context

This was introduced in this PR with the caveat that the name will be reconsidered: https://github.com/ratatui-org/ratatui/pull/395#issuecomment-1685139772

**Comment by orhun** [comment]
I think @joshka's suggestion in that comment makes sense. I can take this one if you also agree.

**Comment by joshka** [comment]
I think there's possibly a little better name for this to be found - but I'm not certain.
Perhaps start with the user in mind and what they'd want this functionality to expose. SegmentSize doesn't seem obvious, and even Allocation doesn't obviously align with how to allocate the excess space available (or fill it, or ...)

**Comment by kdheepak** [comment]
Maybe something that has "preference" or "preferred" in the name?

- `preferred_allocation(AllocationPreferences::DistributeEvenly)`
- `segment_size_preference(SegmentSizePreference::LastTakesRemaining)`

We have to figure out 2 names:

1. Name for the function `segment_size` + name of the enum `SegmentSize`.
2. Name for the variants in the enum, only `EvenDistribution` and `LastTakesRemainder` at the moment

We may want to add more variants to `SegmentSize` in the future. One common one I've found wanting is `TakesRemainder(usize)` where `TakesRemainder(segments.len() - 1)` would do the same thing as `LastTakesRemainder`.

I group all these variants under the name "preference" because I imagine this is always going to be a weak constraint and is going to never be enforced.

**Comment by joshka** [comment]
One concern I have about this is that it bolts more features to a fairly limited layout algorithm (cassowary). We could instead consider whether it's more beneficial to put effort into replacing this with something taffy based.

I say this is "limited" not in the sense that cassowary can't do everything, but in the sense that if we want it to do something the we have to specifically implement that code. I.e. it's possible to add our own growing, shrinking, weighted values, etc. on top of cassowary, but once we write that, then we have to maintain our particular way of laying something out. If instead we accept that flexbox / grid is a reasonable layout approach, and we move towards that then we reduce our maintenance burden.

I case it's not obvious, my favorite type of feature is one that can be implemented by deleting more code than you write.

Either way, I'd suggest that it would be worth listing out the use cases for layout and then go from there rather than evolving it piecemeal.

**Comment by kdheepak** [comment]
I like the idea of moving to taffy. I did even look into it briefly to use taffy directly in my project to work up what a interface would be for users (but didn't get very far).

Do you think we'll be able to maintain the same `Layout` interface with taffy? If yes, then we can pause adding any more features to this. If not, I imagine we might have to integrate taffy with a `TaffyLayout` struct, while keeping the existing `Layout` as is (with deprecated warnings). And then after a few versions or after reasonable amount of time (e.g. 6months?) we can remove the existing `Layout`. My reasoning is that if the interface for users with taffy is going to be different than the existing `Layout` interface, I imagine that will break practically everyone's program with ratatui.

**Comment by joshka** [comment]
> Do you think we'll be able to maintain the same `Layout` interface with taffy?

https://github.com/ratatui-org/ratatui/pull/385 does just that, but the rationale remains that we should think in terms of the use cases that we want to support - it may make sense to replace cassowary and add functionality, or it may make more sense to add Taffy as a secondary option with less focus on backwards compatible interfaces. Designing for the use cases first helps support either option.
