### ISSUE TITLE
The running result of the `paragraph.rs` example does not match the image

### ISSUE THREAD

**Issue by sxyazi** [ratatui-org/ratatui#558]
## Description

Hi, I'm trying to run the [paragraph.rs](https://github.com/ratatui-org/ratatui/blob/main/examples/paragraph.rs) example on [fbf1a45](https://github.com/ratatui-org/ratatui/commit/fbf1a451c85871db598cf1df2ad9a50edbe07cd2), but I'm getting different results from the [example image](https://github.com/ratatui-org/ratatui/tree/main/examples#paragraph).

Specifically, the blue background is no longer extending across the entire line but is only applied to visible characters. I've tried 3 different terminals: kitty, Alacritty, and iTerm2, and none of them have the background covering the entire line.

<img width="885" alt="image" src="https://github.com/ratatui-org/ratatui/assets/17523360/121ba686-da03-4482-af0a-24138bd4831b">

Seems just a documentation mistake?

## To Reproduce

```bash
cargo run --example=paragraph --features=crossterm
```

## Environment

- OS: macOS
- Terminal Emulator: kitty, Alacritty, and iTerm2
- Font: SF Mono
- Crate version: [fbf1a45](https://github.com/ratatui-org/ratatui/commit/fbf1a451c85871db598cf1df2ad9a50edbe07cd2)
- Backend: crossterm

**Comment by kdheepak** [comment]
This should be resolved now! Thanks for bringing it to our attention!

**Comment by joshka** [comment]
The bug was in the image. Caused by a bug in the rendering chain: vhs -> ttyd -> xterm.js.

That bug was recently fixed with the ttyd 1.7.4 release. We need regenerate a bunch of the images and remove the workarounds for the issue from the various examples.

**Comment by kdheepak** [comment]
I can regenerate the examples if you'd like, but how do I think which ones need to be regenerated and what are these workarounds?

**Comment by joshka** [comment]
Search vhs in the commit / file histories.
