### ISSUE TITLE
Table: Allow constructing with &[Row]

### ISSUE THREAD

**Issue by bugnano** [ratatui-org/ratatui#568]
## Problem

I have a list widget that gets constructed in the following way:

```rust
fn build_items() {
    let items: Vec<ListItem> = // Code that constructs the Vec

    draw_items(&items)
}

fn draw_items(items: &[ListItem]) {
    let items = List::new(items)
}
```

And everything works perfectly.

The problem is that the list no longer satisfies my needs, and I need to change the List to a Table.

I tried the following code:

```rust
fn build_items() {
    let items: Vec<Row> = // Code that constructs the Vec

    draw_items(&items)
}

fn draw_items(items: &[Row]) {
    let items = Table::new(items)
}
```

but the code won't compile.

In the Docs, I see that for `List::new` the type is:

```rust
T: Into<Vec<ListItem<'a>>>
```

whereas for `Table::new` the type is:

```rust
T: IntoIterator<Item = Row<'a>>
```

Why this inconsistency?

## Solution

The best solution would be to have consistent data types for constructing all kinds of widgets, so that when one widget no longer fits the needs of the application, it can easily be replaced by another widget.

The problem with this solution would be that it changes the API, thus breaking compatibility.

Another solution would be to provide an alternative constructor to the widgets, so that at least the alternative constructors are consistent between widgets.

**Comment by joshka** [comment]
> The best solution would be to have consistent data types for constructing all kinds of widgets, so that when one widget no longer fits the needs of the application, it can easily be replaced by another widget.

I definitely agree with this, and would break compatibility to promote better consistency. I'm never quite clear on which option is best for this sort of thing in an API. The choices:
- Into<Vec<T>>
- IntoIterator<Item = T>
- AsRef<[T]>
- &[T]
- Vec<T>
- something else?

Then there is a question of whether the items will be used once (i.e. just iterated) or stored in the struct and later used multiple times. And several of the options bring with them questions of lifetime.

If you know of some good guidance on this - I'd definitely read it.

There's a similar PR at https://github.com/ratatui-org/ratatui/pull/557 with the same problem on what to use.

**Comment by joshka** [comment]
Table now supports this (in the 0.26 alpha at least, and in 0.26 to be released this week)
- `Table::new()` accepts IntoIterator<Item = Into<Row<'a>>>
- There is a new FromIterator implementation, which allows you to call `collect()` on any iterator of Into<Row>
