### ISSUE TITLE
[Bug] Error with Hello World example from Book - Paragraph white method not found

### ISSUE THREAD

**Issue by naxmefy** [ratatui-org/ratatui#585]
## Description
`Hello World` example in your book tries to render Paragraph with white on blue - but it seems there is no method found for it.

```rust
Paragraph::new("Hello Ratatui! (press 'q' to quit)")
                    .white()
                    .on_blue(),
```

```log
cargo run
   Compiling wllogv v0.1.0 (/Users/naxmefy/work/dwggroup/rust/wllogv)
error[E0599]: no method named `white` found for struct `Paragraph` in the current scope
   --> src/main.rs:27:22
    |
26  | /                 Paragraph::new("Hello Ratatui! (press 'q' to quit)")
27  | |                     .white()
    | |                     -^^^^^ method not found in `Paragraph<'_>`
    | |_____________________|
    |
    |
   ::: /Users/naxmefy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ratatui-0.23.0/src/style/stylize.rs:128:12
    |
128 |       color!(white);
    |              ----- the method is available for `Paragraph<'_>` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
1   + use ratatui::style::Stylize;
    |

For more information about this error, try `rustc --explain E0599`.
error: could not compile `wllogv` (bin "wllogv") due to previous error
```

## To Reproduce
just follow the guide as explained here: https://ratatui.rs/tutorial/hello-world/index.html#create-a-tui-application

## Expected behavior

Should work as the book/guide explained.

## Screenshots

![image](https://github.com/ratatui-org/ratatui/assets/5736450/347ed9f0-c260-4d1b-b4bf-bdfb7a128c1c)

## Environment

- OS: macOS Ventura 13.5.2 (Apple M1)
- Terminal Emulator: warp v0.2023.10.17.08.03.stable_01
- Font: Fira Code
- Crate version: 0.23.0
- Backend: crossterm

**Comment by joshka** [comment]
These methods are implemented by the Stylize trait which is included in the imports earlier in the page. The error message also notes the same.

**Comment by naxmefy** [comment]
> These methods are implemented by the Stylize trait which is included in the imports earlier in the page. The error message also notes the same.

hmm i see - it was removed, because it was shown as "unused"

![image](https://github.com/ratatui-org/ratatui/assets/5736450/cc817e9f-9aaf-4021-a0e9-e773f9201016)

**Comment by joshka** [comment]
Also note that the docs for this are more up to date in the alpha release:
https://docs.rs/ratatui/0.23.1-alpha.7/ratatui/style/trait.Stylize.html

**Comment by naxmefy** [comment]
it would be nice if this is also explained in the book - at least as hint or sth like that

**Comment by joshka** [comment]
@naxmefy  Thanks - I've incorporated some of the feedback here into https://ratatui.rs/pr-preview/pr-132/tutorial/hello-world/index.html. Specifically, this will add a bit of info about each import, and has a full copy of the source available to view both as a link and in the tutorial.
