### ISSUE TITLE
If a ratatui application is killed, the cursor rests somewhere arbitrarily in the screen

### ISSUE THREAD

**Issue by Thorongil80** [ratatui-org/ratatui#616]
## Problem

I draw a full-screen application in the Terminal using ratatui and crossterm backend on the secondary screen.

If the application is killed hard, the prompt comes arbitrarily within the frame (it seems at latest redraw position, i.e. there where the last time the offscreen buffer drew changes on the screen).

## Solution
After each draw, "park" the cursor in the last line and last column of the outmost frame (usually the initial fullscreen terminal).

Thus on hard kill, the shell prompt should come not within the old screen content but in a new line.

**Comment by joshka** [comment]
Does this still happen if you call LeaveAlternateScreen during a panic hook? See https://ratatui.rs/how-to/develop-apps/setup-panic-hooks.html or https://ratatui.rs/how-to/develop-apps/better-panic-hooks.html for info

**Comment by joshka** [comment]
I'm going to close this out as a won't implement. The right way to handle this is with a panic hook / error hook (a scopeguard would also work).

There's no good way to really handle the cursor in the way that you've suggested as users expect to have control over the cursor right now (I know a few apps that draw mostly with Ratatui, but handle some parts manually for app specific reasons).
