### ISSUE TITLE
Ratatui.rs should have a nice website

### ISSUE THREAD

**Issue by joshka** [ratatui-org/ratatui#620]
# Current State
- [ ] Identify some options for choosing a backend (or backends if we use mdbook and another tool)
- [ ] choose the approach based on the options

# Original issue text
It would be nice to have a landing page rather than ratatui.rs pointing directly at the book, so I slapped together a quick idea using [Zola](https://www.getzola.org/) with the [juice](https://www.getzola.org/themes/juice/) theme. I like the layout / content in [Acton](https://www.acton-lang.org/) as an idea for what we might want to add to a site using the theme in the part after the scroll.

I think we should keep the site and the book in the same repo (perhaps we could rename this repo to website) and build them to a single gh-pages site, putting the book content under `/book`. We'd need to create a header / theme that looks good for both the book and the main site. Currently we have a bunch of themes for this installed on the book, perhaps we could simplify this down to just two (dark/light)?

In theory we could use zola or some other SSG for both the site and docs, but then we'd have to manually write and maintain the things that mdbook gives us for free, so I think it's worth doing only the site part with zola and keeping the book with mdbook.

I've pushed this to https://github.com/joshka/ratatui-book/tree/zola-site if anyone wants to have a play with making this happen.

My preferences for this (unless there's compelling reasons to choose differently):
- the overarching goal should be minimal effort, max result
- static site generator that can push to gh-pages or cloudflare pages, rather than running a service somewhere
- rust based static site generator (e.g. zola) rather than adding extra languages / frameworks
- Minimal Javascript - just what we need for things to work - i.e. no SPA shenanigans or needing node just to build the site
- Site and book should look like they are part of the same site even though they are generated by mdbook / zola
- I'm a fan of dark navy blues and hues related to #102040. Starting the theme from that perspective would be nice to have perhaps with an orange accent?
- I know at least one of the ratatui devs is color blind, so we should this into consideration
- If someone has some ideas about making something compellingly awesome that breaks all these ideas, I'd happily drop a few of these requirements within reason.

Tasks:
- [ ] Create a nice looking landing page
- [ ] Consider whether any of the book pages belong in the site rather than the book (e.g. showcase)
- [ ] Create a header that works for the book and ties in to the main site
- [ ] Create a cohesive theme that works well for site and book (Zola uses SASS for its CSS - perhaps continue that)
- [ ] Update the CI workflows to deploy both site and book

![image](https://github.com/ratatui-org/ratatui-book/assets/381361/79854f48-361f-4b5a-bd85-d673e377811d)

**Comment by joshka** [comment]
> I'd like to throw quarto into the mix for consideration: https://quarto.org/

> Most people in Rust land don't use it.

This seems like a big downside of choosing quarto to me as I like to generally look for tools that have a large user base to draw on when choosing. This makes maintenance easy because usually someone has solved any particular issue already.

**Comment by kdheepak** [comment]
> 2. Aim to find a good tool that does docs + site together and switch from mdbook to that

For clarification, I think Quarto is a good candidate for this particular option. 

> This seems like a big downside of choosing quarto to me as I like to generally look for tools that have a large user base to draw on when choosing. 

For this particular option 2, every alternative (e.g. Docsaurus, MkDocs, etc) is going is few a small number of users relatively. When I get the chance, I'll look for exact projects to get a better sense of the numbers.

> This makes maintenance easy because usually someone has solved any particular issue already.

wrt this, I think because we can write Quarto extensions in Rust, it can make maintenance / feature extension etc easier for rust developers. 

That said, most options are going to be in the same ballpark in terms of features. I'll write down a more high level comparison of our options in a future comment.

**Comment by kdheepak** [comment]
Here's one additional reason I think Quarto + Jupyter Notebooks are appealing.

We can use `evcxr` to run Rust in Jupyter Notebooks. We can make high quality static documentation that contains output of code that is run interactively. Here's some examples I was playing around with:

### Example of importing a dependency:

<img width="808" alt="image" src="https://github.com/ratatui-org/ratatui/assets/1813121/dac20efd-c805-4f26-b88a-9963b3af8c80">

### Example of running Ratatui:

<img width="746" alt="image" src="https://github.com/ratatui-org/ratatui/assets/1813121/d2fb54a2-635c-4e9f-b6f9-6350fcaa1064">

### Built-in auto complete making it easier for writing documentation:

<img width="408" alt="image" src="https://github.com/ratatui-org/ratatui/assets/1813121/28062615-514d-456b-8ce5-73e4d4aa1308">

### Good syntax error messages:

<img width="760" alt="image" src="https://github.com/ratatui-org/ratatui/assets/1813121/c69d7eba-dd58-4ba3-9e77-29be83b4aba4">

### Ability to customize display

<img width="751" alt="image" src="https://github.com/ratatui-org/ratatui/assets/1813121/7d00f17a-efc1-4150-8464-2aae8ce0efc1">

This workflow of using Jupyter Notebooks (or using Quarto + Jupyter execution) works really well for generating technical documentation.

**Comment by kdheepak** [comment]
I did a search on GitHub and found only one project that moved from mdbook to quarto. Related issue https://github.com/rizinorg/book/issues/60 and the code https://github.com/rizinorg/book/tree/dev although I don't believe their transition is complete.

**Comment by kdheepak** [comment]
Another option to consider is use https://starlight.astro.build/

- It is built on top of https://astro.build, which scores very high on web benchmarks
- Markdown based with extensions possible using mdx
- Tauri is moving from Docusaurus (https://tauri.app/) to Starlight (https://beta.tauri.app/): 
- It has features I've wanted, e.g.:

    <img width="730" alt="image" src="https://github.com/ratatui-org/ratatui/assets/1813121/0efa9c5e-7bbb-4e49-8a21-c73caa411e4d">

**Comment by kdheepak** [comment]
There's a number of priorities that I'd thought I'd highlight:

- We want a framework that generates web based content that can deliver:
    - Nice landing page
    - Ability to structure docs in a flexible manner
        - NavBar + Site wide navigation side bar
        - Table of contents for individual pages
        - Navigation buttons (at the bottom)
    - Code highlighting for Rust + additional features 
    - SEO optimized
- Easy to install, easy to generate website locally
- We want to write documentation in Markdown but Markdown has _so_ many flavors
    - Ideally, we would use CommonMark or GFM
    - In practice, we are dependent on what Markdown flavor the framework supports
- Preferably a Rust based framework 
- Popular and well established for writing technical documentation

There are a number of quality of life features that would be nice to have, like

- including code blocks from files
- callout / admonish / aside
- diagram support with mermaidjs / svgbob 
- broken link checking 

Here's a comparison of just two of those attributes:

| Documentation Tool | Language of Framework    | Markdown Flavor Supported           |
|--------------------|--------------------------|-------------------------------------|
| Starlight          | JavaScript/TypeScript    | MDX + custom extensions                                |
| VitePress          | Vue.js/JavaScript        | markdown-it + custom extensions                        |
| Docusaurus         | React/JavaScript         | MDX + custom extensions                                |
| MkDocs             | Python                   | Python Markdown Parser              |
| Sphinx             | Python                   | reStructuredText / Markdown         |
| Read the Docs      | Python                   | reStructuredText / Markdown         |
| MdBook             | Rust                     | Custom Markdown                     |
| Zola               | Rust                     | CommonMark                          |
| Quarto             | JavaScript/TypeScript    | Pandoc markdown / CommonMark                    |

**Comment by kdheepak** [comment]
I don't think there's a single framework that does everything well and meets our priorities and criteria, but here are the ones that I think come close.

1. Quarto

Pros: Most featureful in terms of technical documentation on web, standard Markdown parser, supports extensions in Rust / Lua etc
Cons: Download a .dmg to install, bundles node + pandoc 

2. Zola

Pros: CommonMark Markdown
Cons: Least featureful for writing technical documentations, good for blogs

3. MdBook

Pros: Great for Rust tutorials, walkthroughs etc
Cons: Less featureful, custom Markdown syntax, not good for landing pages

3. Starlight (similar to Docusaurus, VitePress)

Pros: Most featureful in terms of technical documentation on web, heavily web optimized, scores highly in Google Pagespeed, probably great for SEO, interactivity possible through Vue/React/Svelte components
Cons: npm based, mdx + custom markdown flavor

Docusaurus is React, VitePress is Vue, Starlight supports _any_ web framework components using an island approac

5. ReadTheDocs (similar to Sphinx, MkDocs)

Pros: Probably most widely used documentation framework in the world?
Cons: Requires Python to setup, defaults to ReStructuredText instead of Markdown

**Comment by kdheepak** [comment]
I personally don't think having the documentation framework written in Rust is all that valuable (except for easier deployment). I would weight the priority for "having the output be customizable" and "having features that will make for a better website + docs" much higher than "having the documentation generation software written in Rust", as long as alternatives are also easy to deploy on GitHub Actions and iterate on locally.

**Comment by joshka** [comment]
+1 on rust not being the primary constraint. I'd prefer a reasonably well used and modern node based approach over python though. It's worth considering the deployment side of this also. We want to be able to easily generate previews from PRs and deploy them and production to somewhere easy like cloudflare / netlify / perhaps shuttle or fly.io?

100% on needing to support code included from other files somehow.

**Comment by kdheepak** [comment]
> I'd prefer a reasonably well used and modern node based approach over python though. It's worth considering the deployment side of this also. 

I agree! Just having to deal with Python dependencies would make it not worth it. I think reproducible builds is another important item on the list. It would be useful to come back to the project 6 months down the line and not have any builds break.

Also, these node based web frameworks are able to do some optimizations that traditional static site are not doing (e.g. static rendered content + hydration).

>  We want to be able to easily generate previews from PRs and deploy them and production to somewhere easy like cloudflare / netlify / perhaps shuttle or fly.io?

I agree. But I think with GitHub Actions, we can generate html content and push it to cloudflare / netlify, right? 

Feel free to update the comment above for priorities with more things that we would like.

**Comment by joshka** [comment]
Closing this - we accidentally launched an Astro + starlight site.
