### ISSUE TITLE
RFC: Experimental API features

### ISSUE THREAD

**Issue by joshka** [ratatui-org/ratatui#621]
## Problem
It would be nice if we could create changes to the API that we mark as experimental so that features can be added in a way that doesn't need the same amount of care taken for getting it exactly right the first time round. This would allow us to deliver features like #618 with less concern about breaking customer code in the future.

## Solution
This is likely a combination of:
- an `experimental` module - unsure of this or whether we just put the code where it will live - there's pros and cons to both approaches.
- an `experimental` feature - do we want one feature per experiment or one for all experiments?

Does anyone have some ideas about how other crates handle this?

**Comment by mindoodoo** [comment]
I'm curious to know what are some of the pros you see in having an `experimental` module ?

I think the main thing is that experimental features should be opt in. There's an [open rfc issue](https://github.com/rust-lang/rfcs/issues/1491) asking for an `#[unstable]` attribute for library authors, however it does seem quite stale. Alternatively there is also the [`stability`](https://github.com/sagebind/stability) crate which we could try out or create a similar macro. Something quite nice it does is that it expands some doc comments warning that the feature might change.

**Comment by joshka** [comment]
The rationale is that it makes things explicit to the user that the interface may change wildly between releases as the needs of the code changes. It's a "there be dragons" approach. I've seen this used in various libs in other languages to allow for things which will become core to be stabilized close to core.

**Comment by mindoodoo** [comment]
Oh no I mean specifically for the having a specific module for experimental features ? I would tend to think that a feature flag would be enough, and that on the contrary we would probably prefer to have the code for experimental features live in the place that they will live once / if stabilized.

**Comment by joshka** [comment]
Got it. The difference is that if you have an experimental module, then you're able to migrate existing code to the stabilized form without breaking the last version of the experimental (and can mark it as deprecated between that time). Whether that's useful / necessary is the thing to think about

**Comment by joshka** [comment]
@mindoodoo I just saw your star on https://docs.rs/stability/latest/stability/index.html in my GH feed - that looks promising.

**Comment by mindoodoo** [comment]
> Got it. The difference is that if you have an experimental module, then you're able to migrate existing code to the stabilized form without breaking the last version of the experimental

Interesting idea, though I think anyone opting into an experimental part of the crate would be ready to make the changes necessary once the experimental parts are stabilized, especially since they'll need to do it sooner or later if we deprecate and eventually remove the experimental feature in the experimental module.

Yeah stability seems quite nice, I think it does the two main things we want to have :
- Put the feature behind a feature flag
- Add documentation lines explicitly stating it's an experimental feature and might change in the future

I don't know if you can change the doc comments it generates as the ones provided in their examples aren't great

**Comment by joshka** [comment]
https://github.com/ratatui-org/ratatui/pull/633 uses the `stability` crate to hide a method:

I think the doc comments are probably good enough. @mindoodoo What do you think of the following? The Note: ... part is manual, the Availability section is automatically provided.

---
Method docs:

![image](https://github.com/ratatui-org/ratatui/assets/381361/959279dc-bc85-4bc3-817d-9289131a038e)

---

Type docs:

<img width="974" alt="image" src="https://github.com/ratatui-org/ratatui/assets/381361/858034ab-dd6b-4507-8e68-86232919c2a9">

**Comment by mindoodoo** [comment]
Yeah this looks good ! Out of curiosity, do you know if we can configure the *Availability* section ?

**Comment by joshka** [comment]
Nope:

https://github.com/sagebind/stability/blob/master/src/unstable.rs#L26-L34
```rust
				let doc_addendum = format!(
					"\n\
					# Availability\n\
					\n\
					**This API is marked as unstable** and is only available when \
					the `{}` crate feature is enabled. This comes with no stability \
					guarantees, and could be changed or removed at any time.

The tracking issue is: `{}`
				",
```

**Comment by joshka** [comment]
Closing this out as we have an approach that works in using the stability crate. I don't think we need to specifically go with the experimental module approach for now given that works fine.
