### ISSUE TITLE
Implement `From` for `Style`

### ISSUE THREAD

**Issue by Valentin271** [ratatui-org/ratatui#679]
## Problem

There is no way to create a `Style` from crossterm, termion or termwiz style.

This is impossible to implement on the user's side because of the orphan rule. Or super cumbersome with a new-type pattern (not to mention underlying `Color` and attributes have the exact same problem).

It is also impossible to use raw ansi code when creating `Text`, `Line` or `Span` as they will render 
![image](https://github.com/ratatui-org/ratatui/assets/36198422/6e40ed52-dd9c-44e6-ab4a-234d5959e7c9)
Code reference:
![image](https://github.com/ratatui-org/ratatui/assets/36198422/7ffb71ac-3f26-4cfb-aff3-6c0a0cdbd995)

## Solution

Add a `From` impl for `Style`, `Color` and `Modifier`.
These should be under their corresponding terminal feature.

~~We could also authorize raw ansi codes when creating `Text`, `Line`, `Span` and others (if this is possible, don't know the underlying limitations here).~~

EDIT for future readers: [ansi-to-tui](https://crates.io/crates/ansi-to-tui) does exactly that.

## Additional context

I wanted to use https://github.com/sharkdp/lscolors to retrieve `LS_COLORS` and print a list of files.

This could somewhat relate to #493. 

# Tasks

- [x] `crossterm`
- [x] `termion`
- [ ] `termwiz`

**Comment by joshka** [comment]
Definitely a good idea

**Comment by mobley-trent** [comment]
Hello @joshka Is this issue still open for `termwiz` ?

**Comment by joshka** [comment]
Yes. And termion.

**Comment by Valentin271** [comment]
Termion was already done in #692.

Do you want to work on termwiz @mobley-trent?

---

[added a checklist to the original comment]

**Comment by joshka** [comment]
> Termion was already done in https://github.com/ratatui-org/ratatui/pull/692.

Apologies - I forgot.

**Comment by Valentin271** [comment]
Sorry, you didn't reply so I thought you were only checking on :sweat_smile: . I was already working on this at this point ...

If you want to help there is still some interesting work left in the issues list.
