### ISSUE TITLE
impl `From` `Modifier` and `Color` for `Style`

### ISSUE THREAD

**Issue by Valentin271** [ratatui-org/ratatui#694]
## Problem

Often times we need to create simple styling. Currently this requires explicitly creating a `Style` and adding the `Color` or `Modifier`.

e.g.
```rust
Style::default().fg(Color::Red);
// Or with Stylize
Style::default().red();
```

## Solution

This is pretty verbose and could easily be simplified by implementing `From<{Modifier,Color}>` for `Style`

Given a function
```rust
fn style(self, style: Style);
```
We could no write
```diff
+ widget.style(Color::Red.into())
+ widget.style(Modifier::Bold.into())
- wdget.style(Style::default().red())
- wdget.style(Style::default().bold())
```

## Additional context

`Color` could be converted to foreground and background. I think it should convert to foreground. This makes much more sense as we more often want to style an element (i.e. its foreground).

This could help avoid a breaking change in #693.

**Comment by joshka** [comment]
Even better is to then make all the style methods accept `T: Into<Style>` so you get just `.style(Color::Blue)` or `.style((Color::Blue, Modifier::BOLD))`

My additional thought on that aspect is that it would be nice to also accept Option<Style> so we can unset a value (i.e. set to None). This would help in dynamic situations where you might have just one widget in a collection that doesn't need the style that all the others have. I'm not sure if accepting Option<Style> would be somehow compatible with accepting Into<Style>. Perhaps Option<T> or Into<Option<Style>>?

**Comment by Valentin271** [comment]
> Even better is to then make all the style methods accept T: Into<Style> so you get just .style(Color::Blue) or .style((Color::Blue, Modifier::BOLD))

Yep sure. Converting a tuple into style is a good idea too.

Concerning the option, could you develop on a particular usage/example. I don't really see the benefit over using `Reset`.

**Comment by joshka** [comment]
It looks like everywhere that we have styles on widgets they just use Style::default instead of storing it as an Option, so we're ok for now on that (Calendar is the only place we store it as an Option). I was thinking there might was some distinction between Setting a Style to the default vs not setting a style at all, and if so, then it would be nice to be able to explicitly specify None on fields.
