### ISSUE TITLE
Suggestion: When using serde to deserialize a Color, it would be great to use the FromStr implementation

### ISSUE THREAD

**Issue by bugnano** [ratatui-org/ratatui#704]
## Problem
I have a config file that allows configuring colors via strings.
If I use the "serde" feature of the crate, the only accepted color names are the string repr of the Enum variants.

Given that Color implements beautifully the FromStr trait, it would be awesome to be able to use any of the strings supported by FromStr in the config file.

## Solution

Something like:

```rust
impl<'de> Deserialize<'de> for Color {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
        where D: Deserializer<'de>
    {
        let s = String::deserialize(deserializer)?;
        FromStr::from_str(&s).map_err(de::Error::custom)
    }
}

```

## Alternatives
An alternative that I considered is to use the serde_with crate and its DisplayFromStr annotation.
However, annotating every single color is tedious.

**Comment by orhun** [comment]
Hey, thanks for creating this issue!

I personally like this change. I was concerned that casing might be a problem but tried this locally and worked like a charm:

```rs
// still valid
let color: Color = serde_json::from_str("\"Black\"").unwrap();
// this was failing before
let color: Color = serde_json::from_str("\"black\"").unwrap();
```

Would you be interested in creating a PR (along with the tests)?

**Comment by bugnano** [comment]
I already tried creating a PR for this project, but what prevents me to do so is that every commit needs to be signed and I don't want to go through the hassle of setting up GPG and so on.
So if somebody could please implement this feature I'd be happy (or if the contributing policy for this project changes😉).

**Comment by orhun** [comment]
created a PR at #705
