### ISSUE TITLE
State of stateful widgets should be serializable

### ISSUE THREAD

**Issue by MultisampledNight** [ratatui-org/ratatui#711]
## Problem

I'm building a viewer for a relatively long schedule, and want to base that upon `Table`. Since the schedule is soooo looooong and the user is likely to close and open the app several times, I want the user to return to the exact spot of where they were.

However, [`TableState`] is relatively opaque, and doesn't seem to have anything I could use to serialize it.

[`TableState`]: https://docs.rs/ratatui/0.25.0/ratatui/widgets/struct.TableState.html

## Solution
New cargo features `rkyv` and `serde` which implement the respective {de,}serialization traits if enabled. 

## Alternatives

- Vendoring `TableState` into one's own code, implementing the respective traits, and using `TableState::with_offset` + `TableState::with_selected` anytime it needs to be restored
- <missing string table entry since I'm severely out of ideas>

## Additional context

None. I want to implement this though, at least for rkyv.

**Comment by MultisampledNight** [comment]
Turns out there _already is_ a `serde` feature: https://github.com/ratatui-org/ratatui/blob/b0ed658970e8a94f25948c80d511102c197a8f6a/Cargo.toml#L74-L76

I'll extend that one to include state then.

**Comment by joshka** [comment]
Regardingthe rkyv support part of this, it sounds to me that the reason for choosing this over serde is purely a performance thing.

Can you quantify the performance difference here? Is this likely to be a real benefit or one where we go from 0.010ms to 0.005ms for something that is called once in an app's lifetime?

Is there some other benefit I'm missing (i.e. do your already have an app that uses rkyv more generally that is blocked by not having this, or you have a use case where you do need to choose rkyv for wider compatibility reasons and this prevents you from doing so.

These questions might sound a bit pedantic. I'm trying to understand the tradeoff of added maintenance burden vs benefit.
Adding features that are for less commonly used libraries (serde:rkyv ~= 10:1 monthly downloads) and where the maintainers aren't as familiar with them (I'd never heard of rkyv before this issue) adds some extra maintenance burden. E.g. things like breaking serialization formats in new versions of Ratatui, or keeping track of downstream changes.

**Comment by MultisampledNight** [comment]
(seen this pop up and decided it jumps the queue because otherwise I'll forget)

It's not only a performance thing, but also a space/memory efficiency thing! An overview about performance and size benchmarks is available at https://github.com/djkoloski/rust_serialization_benchmark, though it'd be interesting to perform a specific one for ratatui!

Though the zero-copy approach of rkyv is relatively irrelevant in this case, since ratatui can't work with the archived versions of its structs!

Also, it is indeed once in the app's lifetime, but it still needs to be as short as possible, as it may block startup and shutdown if one doesn't want the view to "blink"!

(Personally, I've wanted rkyv support since I'm currently writing a shell protocol that delivers its data over rkyv. But that is a null argument, since it's not public yet and anytime soon. I don't even know if ratatui makes sense in the scenario I'm planning to use my shell protocol in. Feel free to disregard this. /srs)

In effect, the gains are relatively miniscule and probably not worth the effort! I'll close the rkyv PR then!

**Comment by joshka** [comment]
> but also a space/memory efficiency thing

Something I'll repeat ad nauseam is that:

Performance or efficiency gains should rarely be seen as a goal unless the **absolute** value of those gains has a measurable and meaningful effect.

(Basically rephrasing Knuth's quote)

Most things TUI related will tend to be related in some way with order of magnitude calculation that are at most based on the screen resolution. My laptop default term size is about 200x50 = 10K cells. That's a really really small number for just about every algorithm. Looking at the benchmarks linked, serde_json does 1_827_461 (18x 10K) in 3-5ms, which is much less than the human range of detecting. A blink is ~100ms+. Most things below that are instant.

Now if you were serializing and deserializing things every frame, this would change into a problem with a meaningful effect. Or if the absolute one time serialization of this did tend towards that 100ms range, then it would too.
