### ISSUE TITLE
Choose different position for the text in columns in the table widget.

### ISSUE THREAD

**Issue by pythops** [ratatui-org/ratatui#737]
## Problem
I want to be able to choose the position of the text in the columns of a table.
Right now, it seems that the text is always position at the left.

**Comment by joshka** [comment]
Cell accepts Text. Each line in the text has an alignment, which is respected when rendering the cell.

```rust
Cell::new(Line::from("asdf").alignment(Alignment::Right))
```

**Comment by pythops** [comment]
Excellent, I did not see that one. 
Thanks for the answer.
