### ISSUE TITLE
Add Style and Alignment to Text

### ISSUE THREAD

**Issue by joshka** [ratatui-org/ratatui#758]
## Problem
Right now, we can set a style on each line, but not against the entire text. Same with alignment. We can align each line, but not the entire text.

## Solution
- [x] Add style and alignment fields
- [x] Update patch_style and reset_style to modify the style rather than modifying the contained `Line`'s styles.
- [ ] Ensure that all places that render these take these values into account

**Comment by Valentin271** [comment]
`patch_style` and `reset_style` will have to be updated to respectively patch and reset the style in `Text` and not in its internal lines.
