### ISSUE TITLE
Add tick counter to `Frame`

### ISSUE THREAD

**Issue by kdheepak** [ratatui-org/ratatui#764]
## Problem

Every time `Frame` is constructed, it could increment a field `frame_tick` or a `frame_count` variable. This will make it easier to do animations "every 4 frames". This should be a read only field, exposed using a getter function.

`frame_count` could be a `usize` and could roll over to the beginning when it hits it's maximum value.

**Comment by Valentin271** [comment]
> roll over to the beginning when it hits it's maximum value

That would mess up your animation if so right? (no other solutions though I'm just wondering)

Could you elaborate on the benefits of having this _inside_ ratatui instead of having a local counter?

**Comment by kdheepak** [comment]
I personally would find this beneficial when rendering spinners. This lets me divorce the tick rate of the application / number of times draw is called from the animation itself, since I can make the animation widget entirely stateless. And because the animation widget is stateless, the animation can be sync'd across different widgets.

```rust
terminal.draw(|f| { 
    let spinner = vec!["|", "/", "-", "\\"];
    let buffer = f.current_buffer_mut();

    // Determine the current symbol for the spinner
    let symbol_index = f.count() % symbols.len();
    let symbol = symbols[symbol_index];

    // Draw the spinner symbol
    buf.set_string(1, 1, symbol, Style::default());
})?;
```

For simple animations it is trivial to do by having a local counter. But if I have two or more progress bars and one progress bar displays at a later stage, I have to keep track of a global counter of frames otherwise the animations will be de-synced. Having this in Ratatui is definitely a quality of life improvement.

I think there's probably also debugging benefits here, it is easier to make a FPS counter widget etc.

**Comment by Valentin271** [comment]
> For simple animations it is trivial to do by having a local counter

Alright this was my main doubt but you convinced me :)

**Comment by kdheepak** [comment]
> > roll over to the beginning when it hits it's maximum value

> That would mess up your animation if so right? (no other solutions though I'm just wondering)

I made a PR for this around the same time as your comment. I ended up using `u64` which has a max value of 18_446_744_073_709_551_615. Even with a 60 fps rendering app, it would take 100 million years to roll over :) `u32` would also be in the order of a hundred years.

**Comment by Valentin271** [comment]
> I made a PR for this around the same time as your comment. I ended up using u64 which has a max value of 18_446_744_073_709_551_615. Even with a 60 fps rendering app, it would take 100 million years to roll over :) u32 would also be in the order of a hundred years.

That's exactly what I was calculating before approving your PR :smile:, thanks

**Comment by kdheepak** [comment]
<img width="305" alt="image" src="https://github.com/ratatui-org/ratatui/assets/1813121/5f50bef1-a36d-41d6-b57e-f8fd094c5043">

**Comment by kdheepak** [comment]
My math in the previous comment was wrong. `u32` would be 2 years vs `u64` 9.7 billion years.
