### ISSUE TITLE
Highlight symbol should be `Text` or `Cell`

### ISSUE THREAD

**Issue by kdheepak** [ratatui-org/ratatui#777]
In this image, the dot in the top left is the highlight symbol.

<img width="756" alt="image" src="https://github.com/ratatui-org/ratatui/assets/1813121/f1aeaa5c-8463-404e-a986-1dc62d377ede">

This table renders 3 `Line` as the `Text` for each `Row` and the height of each `Row` is 3. 

Currently it doesn't seem like it is possible to make the highlight symbol for the selected line to be inline with the middle line of the row. This would be possible if highlight symbol was a `Text` or `Cell`.

Thanks to @joshka for the idea.

**Comment by joshka** [comment]
I went with just text for now figuring that using Cell would make it difficult to keep the repeat symbol behavior. But after I did this I realized that was just on List, not table.

**Comment by Valentin271** [comment]
Closing this as it is fixed by #781
