### ISSUE TITLE
Update table example

### ISSUE THREAD

**Issue by joshka** [ratatui-org/ratatui#800]
## Problem
In #781 we tweaked the table example a bit to use a nicer layout and colors.
The example image has not been updated yet in the readme.
Before we do, this example needs to be a bit less frantic (mostly just slow down the key presses in the tape file for this).

  ![Made with VHS](https://vhs.charm.sh/vhs-6z75EkofPu13czwIq1ZhYw.gif)

It would be nice to add a scrollbar to the example too, and tweak the colors from the new material design or tailwind palette modules.

## Solution

- [ ] update the example
- [ ] tweak the vhs tape and generate a new image
- [ ] PR for the main repo updating the example
- [ ] PR for the /images branch with the new image
- [ ] Update the website example https://ratatui.rs/showcase/widgets/#table

**Comment by Emivvvvv** [comment]
I did the first three in the PR: https://github.com/ratatui-org/ratatui/pull/840. 

However, I can't update the gif in the images branch. I get this error when I try to push my changes.
```
[cargo-make] INFO - cargo make 0.37.7
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: ci
[cargo-make] INFO - Profile: development
[cargo-make] ERROR - Task ci not found
[cargo-make] WARN - Build Failed.
error: failed to push some refs to 'https://github.com/Emivvvvv/ratatui.git'
```

I also wanted to update website's example but `style::palette::material` is not available for rataui 0.25.0 but I'm using that for new table example
```
const EXAMPLE_TABLE_COLORS: [material::AccentedPalette; 4] = [material::RED, ...];
...
let normal_row_color = curr_color.c600;
let alt_row_color = curr_color.c400;
```

**Comment by orhun** [comment]
My guess is you probably have some git hooks set up and `git push` is unable to run them on the `images` branch.

**Comment by Emivvvvv** [comment]
`git push --no-verify` worked 👍🏻

**Comment by Emivvvvv** [comment]
And for the website, I guess I need to add more things to put my code because of that color change ability.

> though if they are more advanced than the ones already in this repo (i.e. require anything beyond just rendering), you may need to add another binary to the source project.

**Comment by joshka** [comment]
Apologies. The workflow for updating example images isn't great - it's optimized for maintainers over contributors because it isn't an area that has had much external contribution. We're happy to run the vhs scripts if needed to regen the images, or take PRs on that branch.

Down the line, it could be worth considering moving the example images into the website repo (which uses git-lfs to store the images, and then deploys them to cloudflare)
