### ISSUE TITLE
Implement Widget for Text

### ISSUE THREAD

**Issue by joshka** [ratatui-org/ratatui#801]
## Problem
When composing custom widgets, it's common to have configurable fields that are Text / Line / Span.
Sometimes we don't really need to make a full paragraph widget to render these (as the custom widget might not need wrapping, blocks, etc.)

## Solution

Implement a simplified Widget for Text that just renders each line to the area.

This might be as simple as
```rust
fn render(area: Rect, buf: &mut Buffer) {
  for (line, row) in self.lines.zip(area.rows()) {
    line.render(row, buf);
  }
}
```

- [ ] add unit tests
- [ ] add doc comments on Text about when to use Paragraph rather than Text and note the missing functionality
- [ ] Look for examples that can be updated to the new approach

## Additional context
Eventually if we move the line wrapping code onto Text / Line, this rendering will support line wrapping. It could be worth noting this in the doc comments.
Paragraph will still exist long term to be able to supply the various other functionality like Blocks, Scrolling, etc.

**Comment by Valentin271** [comment]
I think we can close this because #758 implies that already ("the check everything works" part mainly)

**Comment by joshka** [comment]
Mostly I wanted to keep this open for any design decisions that need to be made (and in case someone external wanted to contribute a first issue).
#758 is about style and patch style, not so much the widget impl.

**Comment by Valentin271** [comment]
> 758 is about style and patch style, not so much the widget impl

Yes but making sure every widget respects style and alignment without implementing Widget on Text is a bad idea.

We can keep this open but I'll do both at the same time.
