### ISSUE TITLE
implement `Display` for `Text`, `Line`, `Span`

### ISSUE THREAD

**Issue by Valentin271** [ratatui-org/ratatui#816]
## Problem
Someone on discord wanted to check the actual content of a `Text`, ignoring the style.

One solution is to loop over the inner lines and span manually. I'm wondering if implementing `Display` is worth it to get a string representation of `Text`?

## Solution

Implement `Display` for `Text`, `Line` and `Span` at least.

## Alternatives
Just let users code it themselves as the fields are all public and this might not be a wide use case.

**Comment by orhun** [comment]
I remember hitting the same case in the past. I think that the `Display` implementation or a method such as `raw_text()` would be nice.

**Comment by Valentin271** [comment]
Sure go ahead @Emivvvvv
