### ISSUE TITLE
Improve Tabs examples

### ISSUE THREAD

**Issue by joshka** [ratatui-org/ratatui#819]
## Problem
In the new Constraints example, a really neat approach to implementing tabs using enums was used. I like it because it avoids using strings, so it's easy to follow how the pieces work together.

This would make a really good example for the API docs, and could be expanded into a howto article on the website easily.

https://github.com/ratatui-org/ratatui/blob/cc6737b8bc09d254413adc1cbf2bc62d2f93792d/examples/constraints.rs#L114-L131

## Solution
Write this up for:
- [ ] api docs on the `Tabs` widget
- [ ] more detailed how-to article on the website

**Comment by Emivvvvv** [comment]
We can also rewrite `Tabs` example. I think I can work on this task in this order.

- [ ] API docs on the Tabs widget
- [ ] Rewrite `Tabs` example following this Issue: https://github.com/ratatui-org/ratatui/issues/846
- [ ] More detailed how-to article on the website

**Comment by joshka** [comment]
Go for it. Sounds great.

The caveat is I'd focus on making the Tabs usage clear and clean be the primary goal. Make it Pretty is secondary to that.

It wouldn't hurt to pick something interesting for the tab contents, but only if it's also fairly short.

On the pretty front, I've been trying to get away from using borders where they're unnecessary. Think about how web design uses borders rarely. Look at demo2, flex, and constraints examples for some ideas. 

Last think about where you want to split the example vs how to guides vs docs. There's also a missing showcase item for the website that would be nice to see https://ratatui.rs/showcase/widgets/

The best bit about this task is tabs is the most in need of a rewrite, so as long as it's clean anything is better than what we have. (There's some observations about code quality at https://discord.com/channels/1070692720437383208/1070692720437383211/1197915965107753020 and reading the conversation after that point.)

**Comment by Emivvvvv** [comment]
I wanted to rewrite the `Tabs` example first before touching the API documents to see if I understand the general idea or not.

**Comment by Emivvvvv** [comment]
About API docs update:

Is something like this enough?

```
/// Also with using enums, more organized code could be achieved. In this example, we used enums to
/// generate titles but they can also be used to decide what to render with a `match` expression.
///
/// ```
/// use strum::{Display, EnumIter, IntoEnumIterator};
/// use ratatui::widgets::Tabs;
///
/// #[derive(Clone, Copy, Display, EnumIter)]
/// enum SelectedTab {
///     Tab0,
///     Tab1,
/// }
///
/// Tabs::new(SelectedTab::iter().map(|tab_title| format!("{tab_title}")));
/// ```
```

Or would you like to see an example for this sentence `they can also be used to decide what to render with a match expression.`? Something like the part you put from [constraints.rs](https://github.com/ratatui-org/ratatui/blob/cc6737b8bc09d254413adc1cbf2bc62d2f93792d/examples/constraints.rs#L114-L131). Maybe something a little bit easier? I'll move forward and create a PR after hearing your opinions.

**Comment by joshka** [comment]
For the API docs, it's probably worth calling out the idea generally and pointing to the example / website how to article for more info.

Something like (rephrase to be a bit better linguistically)
- It can be convenient to use an enum to represent the titles, and then implement Widget on the enum to provide information on how to render each tab. See ... and ... for more details on this approach.
