### ISSUE TITLE
Deprecate `SegmentSize` on `Table`

### ISSUE THREAD

**Issue by kdheepak** [ratatui-org/ratatui#835]
Currently table uses `SegmentSize`: 

https://github.com/ratatui-org/ratatui/blob/9df6cebb58e97ac795868fa0af96a8aaf9c794c0/src/widgets/table/table.rs#L540-L569

but we would like to deprecate that in favor of `Flex`. 

- Add new `flex` method with `flex` field
- Change `segment_size` method to use `flex` method
- Deprecate `segment_size` method and remove `segment_size` field
- Update documentation 

See this PR for reference:

https://github.com/ratatui-org/ratatui/pull/804

**Comment by Emivvvvv** [comment]
This also means

```
/// Controls how to distribute extra space among the columns
segment_size: SegmentSize,
```
```
fn default() -> Self {
        Self {
            ...
            segment_size: SegmentSize::None,
        }
    }
```

will also be changed to (including all other usages of segment_size and SegmentSize)

```
/// Controls how to distribute extra space among the columns
flex: Flex,
```
```
fn default() -> Self {
        Self {
            ...
            flex: Flex::Start,
        }
    }
```
right? Or I understand wrongly.

**Comment by Emivvvvv** [comment]
Yeah makes sense. Thanks for explaining! 🚀
