### ISSUE TITLE
Add Alignment convenience methods to Line, Text and Paragraph (and perhaps Span).

### ISSUE THREAD

**Issue by joshka** [ratatui-org/ratatui#853]
## Problem
Creating a centered or right aligned line / text / paragraph is currently a little verbose:

```rust
Line::raw("foo").alignment(Alignment::Center);
Text::raw("foo").alignment(Alignment::Center);
Paragraph::new("foo").alignment(Alignment::Center);
```

Aligning a span means converting to a line first:
```rust
Line::from(Span::raw("foo")).alignment(Alignment::Center);
```

## Solution
Add several setter methods to Line, Text and Paragraph for each alignment:
- `fn left_aligned(self) -> Self`
- `fn centered(self) -> Self`
- `fn right_aligned(self) -> Self`

```rust
Line::raw("foo").left_aligned();
Text::raw("foo").centered();
Paragraph::new("foo").right_aligned();
```

Add the same methods on span which will convert the span into a Line:
- `fn left_aligned(self) -> Line<'a>`
- `fn centered(self) -> Line<'a>`
- `fn right_aligned(self) -> Line<'a>`

## Implementation

- [ ] simple unit tests for each method (e.g. `let line = Line::default().centered(); assert_eq!(line.alignment, Alignment::Center)`
- [ ] docs for each mentioning this as a convenience shortcut
- [ ] docs for methods on each struct
- [ ] replace example code that calls `.alignment(Alignment::*)` with new calls
- [ ] replace code in website examples

This should be a non-breaking change that could be released in a point release rather than a major release.

## Alternatives
This could be implemented as an extension trait like Stylize, but I think it would be easier to understand the implementation if these methods were just repeated.

## Additional context
Marked as a Good First Issue for newcomers. Please read the [Contribution Guidelines](https://github.com/ratatui-org/ratatui/blob/main/CONTRIBUTING.md) for some help getting started, and don't hesitate to reach out for more questions on this here or on the the [feature discussion](https://discord.com/channels/1070692720437383208/1072879985762762812) discord channel.

**Comment by Eeelco** [comment]
I would like to work on this issue, could you assign it to me please?
