### ISSUE TITLE
Add documentation to Text 

### ISSUE THREAD

**Issue by joshka** [ratatui-org/ratatui#854]
## Problem
In 0.25.0 the Span docs were updated to have a list of constructor, setter and other methods. In 0.26 the Line docs have been updated too. This helps give an overview of the relevant methods that make up the types. We haven't done the same for Text yet.

- https://docs.rs/ratatui/latest/ratatui/text/struct.Span.html
- https://docs.rs/ratatui/0.26.0-alpha.2/ratatui/text/struct.Line.html
- https://docs.rs/ratatui/0.26.0-alpha.2/ratatui/text/struct.Text.html

## Solution
- [ ] Add docs similar to the docs in Line and Span to the Text struct to document the methods

## Alternatives
None

## Additional context
Marked as a Good First Issue for newcomers. Please read the [Contribution Guidelines](https://github.com/ratatui-org/ratatui/blob/main/CONTRIBUTING.md) for some help getting started, and don't hesitate to reach out for more questions on this here or on the the [feature discussion](https://discord.com/channels/1070692720437383208/1072879985762762812) discord channel.

**Comment by Valentin271** [comment]
Closing as this was completed in #857.
