### ISSUE TITLE
Rename `Constraint::Proportional` to `Constraint::Fill`

### ISSUE THREAD

**Issue by kdheepak** [ratatui-org/ratatui#859]
https://github.com/ratatui-org/ratatui/pull/783 introduced `Proportional` before spacing and `Flex` were implemented. 

With `Flex` it's easier to fill empty spaces in commonly used patterns.

```rust
Layout::horizontal([Fixed(10), Proportional(1), Fixed(10)])
Layout::horizontal([Proportional(1), Fixed(10), Proportional(1), Fixed(10), Proportional(1)])
Layout::horizontal([Fixed(10), Fixed(10), Proportional(1)])
Layout::horizontal([Proportional(1), Fixed(10), Fixed(10), Proportional(1)])
Layout::horizontal([Proportional(1), Fixed(10), Fixed(10)])
```

can now be written as:

```rust
Layout::horizontal([Fixed(10), Fixed(10)]).flex(Flex::SpaceBetween)
Layout::horizontal([Fixed(10), Fixed(10)]).flex(Flex::SpaceAround)
Layout::horizontal([Fixed(10), Fixed(10)]).flex(Flex::Start)
Layout::horizontal([Fixed(10), Fixed(10)]).flex(Flex::Center)
Layout::horizontal([Fixed(10), Fixed(10)]).flex(Flex::End)
```

With https://github.com/ratatui-org/ratatui/pull/788, it is also possible to return spacers from split. 

What was previously done with `Proportional` to fill empty spaces:

<img width="567" alt="image" src="https://github.com/ratatui-org/ratatui/assets/1813121/9f71a8a9-cce6-4ca5-8fb4-1f67417fcbdf">

Can now be done with `Flex` and spacers:

<img width="568" alt="image" src="https://github.com/ratatui-org/ratatui/assets/1813121/59dfd509-6f79-4b28-a828-71a96511e4df">

https://github.com/ratatui-org/ratatui/pull/788 also reworks the implementation and with the new weights.
Both proportionals and spacers grow in the same way, and we have to prioritize one or the other for stable solutions. So when used together, either proportionals are zero or spacers can zero. 

This is also a documentation related issue, because we will have to teach users how proportionals and spacers work.

However, one unique feature of `Proportional` is the ability to scale proportionally.

```rust
Layout::horizontal([Proportional(1), Fixed(10), Proportional(2)])
```

This is not quite so straightforward to achieve without `Proportional`. 

<img width="566" alt="image" src="https://github.com/ratatui-org/ratatui/assets/1813121/822c4b71-3ade-4f77-9a82-cace09f2f3e2">

This issue is to discuss whether this feature is worth it to keep `Proportional` around.

**Comment by joshka** [comment]
> However, one unique feature of Proportional is the ability to scale proportionally.

I do like having this ability, and reading a bit more on flex at https://developer.mozilla.org/en-US/docs/Web/CSS/flex and https://developer.mozilla.org/en-US/docs/Web/CSS/flex-grow suggests that a more appropriate name for this might be `FlexGrow`? What about keeping `Proportional`, but renaming it?

But we also venture into the path here of eventually trying to rewrite taffy on top of cassowary, which seems foolish. In fact, a question I've been asking myself about some of this recent work is whether there's an alternative approach that maps the existing constraints onto some basic flex behavior in taffy, but then opens up the entire taffy flex model to be used. By implementing our own incompatible version of this we may never be able to do that without breaking. Do you have thoughts on that at all?

**Comment by kdheepak** [comment]
> But we also venture into the path here of eventually trying to rewrite taffy on top of cassowary, which seems foolish.

I agree that we want to move to taffy eventually. I _think_ everything we have right now maps to `flex` concepts and can be ported to taffy without breaking "conceptually". But I don't think we'd be able to move to taffy without changing the tests (because a lot of tests are specification tests and a lot of them test various corner cases). 

In terms of user experience, we _could_ try to get the same interface working with the current layout and taffy, though I'm sure a number of niche cases may come up that don't map quite as nicely. For example, I don't quite know the priorities for flex-basis / flex-grow / flex-shrink (equivalent to `Min(x)` and `Max(x)` and how that is affected by absolute values (equivalent to `Length(x)`). 

I also think when we move to taffy we want to make it easier to build 2-D layouts. Maybe something like this:

```rust
let (header, main, footer) = area.split(&Layout::vertical([Min(3), Percentage(100), Min(3)]);
let (sidebar, content) = main.split(&Layout::horizontal([Length(30), Proportional(1)]);
```

could be written like this instead?

```rust
let (header, sidebar, content, footer) = area.split(&Layout::grid(r#"
    header header header
    sidebar content content
    footer footer footer
"#))
```

I'm assuming that moving to taffy will involve breaking changes to either the API and/or behaviour, and we should strive to minimize it as much as possible. I'm assuming there will be a number of things that will be unavoidable though.

We'll probably want to deprecate the current layout over a few releases or support both for a while as we move from soft recommending taffy to hard recommending it to only supporting taffy.

**Comment by joshka** [comment]
> We'll probably want to deprecate the current layout over a few releases or support both for a while as we move from soft recommending taffy to hard recommending it to only supporting taffy.

I'd imaging we should keep this forever and just add a second layout module instead (`mod flex`, or `mod taffy_layout`)

**Comment by kdheepak** [comment]
> Personally, the API I'd like to see would be `Constraint::Fill(u16)`, where the `u16` is a "pressure" argument used when multiple `Fill`s are present; e.g., `Fill(2)` is assigned twice as much size as `Fill(1)`.

_Originally posted by @jwodder in https://github.com/ratatui-org/ratatui/discussions/631#discussioncomment-7600915_

Sounds like this is exactly what `Proportional` does, so I anticipate the scaling proportionally feature could be useful all on its own.

**Comment by joshka** [comment]
Can you remind me why we went with Proportional over Fill for this?

**Comment by kdheepak** [comment]
It was first called `Flex`, then I changed it to `Fill` and then changed it to `Proportional` in this PR: https://github.com/ratatui-org/ratatui/pull/783

Most of the discussion about the naming seems to have happened on Discord in a private channel. I've summarized some relevant parts of the discussion here:

> joshka: You mentioned Proportional to indicate "relatively sized" segments. Did you consider Relative as a name - it's a good counter point to Fixed (though Absolute might be the perfect antonym)

> kd: I don't think Relative conveys the nuances of how this constraint works
> It is lower priority that all other constraints and only fills excess space.
> It is proportional / scaled with respect to other Fill constraints
> e.g. [Fill(1), Ratio(1, 4)] reads better to me than [Relative(1), Ratio(1, 4)]

> joshka: Perhaps then your point about calling it Auto could still be right?

> joshka: I think Fill is ok based on thinking it through.

> kd: Do you feel Fill(scaling_factor) is not obvious? 
> For me [Fill(1), Fill(2), Fill(3)] scales the first segment once, the second segment twice, the third segment thrice.
> It's also easier to explain to users imo and more obvious when you think of the math.

> kd: Fill best describes it's behavior.
> Proportional best describes the implementation.

> joshka: Linguistically, we have a length constraint, a minimum constraint, a percentage constraint, a maximum constraint, a ratio constraint.
> A fill constraint seems to not fit.

> kd: Here's a summary of the discussion + my ranking:
> - Flex: Behavior has some similar semantics to flexbox, short name
> - Auto: Behaviour has very similar semantics to flex auto, short name, name read in isolation may not be clear
> - Proportional: Most accurate to implementation, describes secondary behavior
> - Fill: Describes primary behavior
> - Relative: It's relatives are proportional to it in size? This describes secondary behavior
> - Scale: Describes secondary behavior
> - Spread: Describes primary behavior

> joshka: We're talking about putting names to something that describes a constraint. The holes are constraints on the blocks. We're looking for how to name the square hole 
> Of your list, Proportional fits best with the idea that it is a constraint.

> kd: I like Proportional and I also like Fit a lot. Still not sold on Relative

**Comment by kdheepak** [comment]
Do we want to change `Proportional` to `Fill` then? We can repurpose this issue to be `Rename` instead of `Remove`.

**Comment by joshka** [comment]
yep
