### ISSUE TITLE
Add a Rect contains function for Position / (u16, u16)

### ISSUE THREAD

**Issue by Laocoon7** [ratatui-org/ratatui#921]
## Problem
There is no way to determine if a `Position` is inside a `Rect`

## Solution
Add a `contains` method to `Rect`

## Alternatives
We can currently write our own `if position.x >= rect.left() && position.x < rect.right()...` in a separate function, or copy/paste it all over our code. The other option is to create a `let position_rect = Rect::new(position.x, position.y, 1, 1)` and use `rect.intersects(position_rect)`

## Additional context
This is a simple building block for handling external input inside a widget.

As my `Position` derives from other crates, I prefer a `pub fn contains(&self, x: u16, y: u16) -> bool` which keeps it in line with `buf.get_mut(x: u16, y: u16)` over using `ratatui::prelude::Position` though some consideration could be put into also adding a `pub fn contains_position(&self, position: Position) -> bool` or similar.

**Comment by joshka** [comment]
https://docs.rs/ratatui/latest/ratatui/layout/struct.Rect.html#method.contains was added in 0.26. Does this work for you?

**Comment by Laocoon7** [comment]
That's exactly what I was looking for. I added main branch to my project last week for the `Constraint` changes. I see it was added shortly after that. Thank you!
