### ISSUE TITLE
syn 1.x dependency reintroduced in 0.25 via stability crate

### ISSUE THREAD

**Issue by extrawurst** [ratatui-org/ratatui#961]
`0.25` adds `stability` crate as a dependency which seems rather unmaintained and still depends on old `syn 1.x`.

is there an alternative that is more maintained and up to date? or is there a chance to get this update upstreamed into `stabilty`?

**Comment by orhun** [comment]
I'm guessing the reason why we depend on `stability` crate is that Rust does not support stability attributes (such as `#[unstable(...)]`) outside of the standard library. See <https://github.com/rust-lang/rfcs/issues/1491>

I looked around in the Rust ecosystem a bit for a maintained alternative of `stability` crate but couldn't find anything. (Let me know if you know something!) So I believe I think it is best to upstream some changes for putting `stability` in a better shape.

**Comment by orhun** [comment]
I updated the `syn` dependency in https://github.com/sagebind/stability/pull/8, hopefully the maintainer will respond soon.

**Comment by orhun** [comment]
Seems like that the maintainer of `stability` is not responding. Should fork it and release a new version on crates.io to get this moving? I looked for alternative crates but couldn't find any.

**Comment by extrawurst** [comment]
@orhun that would be great 👍

**Comment by joshka** [comment]
> Seems like that the maintainer of `stability` is not responding. Should fork it and release a new version on crates.io to get this moving? I looked for alternative crates but couldn't find any.

Looks like they are still fairly active on github, so it may just be a time thing. I'd generally prefer to work out a way that avoids forking something like this. Perhaps @sagebind would be amenable to adding one of us as a secondary maintainer? Can you reach out via email / socials?

If this wasn't a proc macro I'd just say bring in the source code directly and use it. But we'd need a separate library for this. It's a shame `ratatui-macros` is already taken (that probably should have been named `tui-macros`) as that would be a good place for proc macros that are necessary to be able to build ratatui like this to live.

**Comment by sww1235** [comment]
looks like this was fixed in commit #b5061c5. Thanks for prodding sagebind XD.
