### ISSUE TITLE
Paragraph wrapped in a block can not be styled as expected

### ISSUE THREAD

**Issue by PierreQuebriac** [ratatui-org/ratatui#990]
## Description
I was following the tutorial on the JSON editor: [https://ratatui.rs/tutorials/json-editor/](https://ratatui.rs/tutorials/json-editor/) and noticed a dissimilarity of result after compilation on the  [title](https://ratatui.rs/tutorials/json-editor/ui-main/#the-title) step.

The tutorial offer to write this:
```rs
    let title_block = Block::default()
        .borders(Borders::ALL)
        .style(Style::default());

    let title = Paragraph::new(Text::styled(
        "Create New Json",
        Style::default().fg(Color::Green),
    ))
    .block(title_block);

    f.render_widget(title, chunks[0]);
```

And I was expecting to get a box with white borders surrounding a green text saying "Create new JSON" and after compilation I got a box with white borders and a **white** text.

## To Reproduce
The easiest way to reproduce was to download the raratui website app [here](https://github.com/ratatui-org/ratatui-website/tree/main/code/ratatui-json-editor-app) and run `cargo run`

## Expected behavior
I was expected that a code like this
```rs
let title = Paragraph::new(Text::styled(
        "Create New Json",
        Style::default().fg(Color::Green),
    ))
    .block(
        Block::default()
            .borders(Borders::ALL)
            .style(Style::default()),
    );
```

would provide a white border box with a green text inside.

## Screenshots
![issue_screenshot](https://github.com/ratatui-org/ratatui/assets/72198491/230d579b-9820-4b80-8c25-adc3c3b1a523)

## Environment
- OS: Linux
- Terminal Emulator: xterm
- Font: Monospace
- Crate version: 0.26.1
- Backend: crossterm

## Additional context
I noticed that in version 0.25.0 this bug does not happen

Thanks for helping me !

**Comment by orhun** [comment]
Changing `Text` to `Line` fixes this:

```diff
diff --git a/code/ratatui-json-editor-app/src/ui.rs b/code/ratatui-json-editor-app/src/ui.rs
index edccbaa..8b47d4d 100644
--- a/code/ratatui-json-editor-app/src/ui.rs
+++ b/code/ratatui-json-editor-app/src/ui.rs
@@ -29,7 +29,7 @@ pub fn ui(f: &mut Frame, app: &App) {
         .borders(Borders::ALL)
         .style(Style::default());
 
-    let title = Paragraph::new(Text::styled(
+    let title = Paragraph::new(Line::styled(
         "Create New Json",
         Style::default().fg(Color::Green),
     ))
```

But yeah,  I'd also expect `Text::styled` to apply the style as well. Not sure what's going on there.

**Comment by PierreQuebriac** [comment]
It works ! Thank you for your help !
